# appstreamcli-compose
# Autogenerated from man page /usr/share/man/man1/appstreamcli-compose.1.gz
complete -c appstreamcli-compose -l origin -d 'Set the AppStream data origin identifier'
complete -c appstreamcli-compose -l result-root -d 'Sets the directory where all generated output that is deployed to a user\\*(Aq…'
complete -c appstreamcli-compose -l data-dir -d 'Override the directory where the generated AppStream metadata catalog will be…'
complete -c appstreamcli-compose -l icons-dir -d 'Override the directory where the cached icons are exported to'
complete -c appstreamcli-compose -l hints-dir -d 'Set a directory where hints reported generated during metadata processing are…'
complete -c appstreamcli-compose -l media-dir -d 'If set, creates a directory with media content (icons, screenshots, '
complete -c appstreamcli-compose -l media-baseurl -d 'The URL under which the contents of a directory set via --media-dir will be s…'
complete -c appstreamcli-compose -l prefix -d 'Set the default prefix that is used in the processed directories'
complete -c appstreamcli-compose -l print-report -d 'Print the issue hints report (that gets exported as HTML and YAML document wh…'
complete -c appstreamcli-compose -l no-partial-urls -d 'If set, all URLs in the generated data will be absolute and media_baseurl wil…'
complete -c appstreamcli-compose -l icon-policy -d 'Override the existing icon policy with a custom one'
complete -c appstreamcli-compose -l allow-custom -d 'By default, all custom entries set in MetaInfo input data are removed'
complete -c appstreamcli-compose -l components -d 'Set a comma-separated list of AppStream component IDs that should be consider…'
complete -c appstreamcli-compose -l no-color -d 'Don\\*(Aqt print colored output'
complete -c appstreamcli-compose -l verbose -d 'Display extra debugging information'
complete -c appstreamcli-compose -l version -d 'Display the version number of appstreamcli compose'

