# asciidoctor
# Autogenerated from man page /usr/share/man/man1/asciidoctor.1.gz
complete -c asciidoctor -s B -l base-dir
complete -c asciidoctor -s S -l safe-mode
complete -c asciidoctor -l safe
complete -c asciidoctor -s a -l attribute
complete -c asciidoctor -s b -l backend
complete -c asciidoctor -s d -l doctype
complete -c asciidoctor -s D -l destination-dir
complete -c asciidoctor -s E -l template-engine
complete -c asciidoctor -s e -l embedded
complete -c asciidoctor -s I -l load-path
complete -c asciidoctor -s n -l section-numbers
complete -c asciidoctor -s o -l out-file
complete -c asciidoctor -s R -l source-dir
complete -c asciidoctor -s r -l require
complete -c asciidoctor -s s -l no-header-footer
complete -c asciidoctor -s T -l template-dir
complete -c asciidoctor -l failure-level
complete -c asciidoctor -s q -l quiet
complete -c asciidoctor -l trace
complete -c asciidoctor -s v -l verbose
complete -c asciidoctor -s w -l warnings
complete -c asciidoctor -s t -l timings
complete -c asciidoctor -s h -l help
complete -c asciidoctor -s V -l version

