# awesome
# Autogenerated from man page /usr/share/man/man1/awesome.1.gz
complete -c awesome -s v -l version
complete -c awesome -s h -l help
complete -c awesome -s c -l config
complete -c awesome -s k -l check
complete -c awesome -l search
complete -c awesome -s a -l no-argb
complete -c awesome -s m -l screen
complete -c awesome -s r -l replace

