# brotli
# Autogenerated from man page /usr/share/man/man1/brotli.1.gz
complete -c brotli -l rm
complete -c brotli -l decompress -d '[bu] 2'
complete -c brotli -l test -d 'equivalent to [lq]--decompress --stdout[rq] except that the decompressed data…'
complete -c brotli -l suffix
complete -c brotli -s '#' -d 'slower compression [bu] 2'
complete -c brotli -s c -l stdout -d '[bu] 2'
complete -c brotli -s d -d '[bu] 2'
complete -c brotli -s f -l force -d '[bu] 2'
complete -c brotli -s h -l help -d '[bu] 2'
complete -c brotli -s j -d '(1)-like behaviour [bu] 2'
complete -c brotli -s k -l keep -d '(1)-like behaviour [bu] 2'
complete -c brotli -s n -l no-copy-stat -d 'attributes [bu] 2'
complete -c brotli -s o -l output -d 'there is a single input entry [bu] 2'
complete -c brotli -s q -l quality -d 'bigger values cause denser, but slower compression [bu] 2'
complete -c brotli -s t -d '[bu] 2'
complete -c brotli -s v -l verbose -d '[bu] 2'
complete -c brotli -s w -l lgwin -d '(default: 24); window size is (pow(2, NUM) - 16); 0 lets compressor decide ov…'
complete -c brotli -s D -l dictionary -d 'dictionary; same dictionary MUST be used both for compression and decompressi…'
complete -c brotli -s S -d 'br) [bu] 2'
complete -c brotli -s V -l version -d '[bu] 2'
complete -c brotli -s Z -l best -d 'same as [lq]-q 11[rq] SEE ALSO'

