# bundle-gem
# Autogenerated from man page /usr/share/man/man1/bundle-gem.1.gz
complete -c bundle-gem -l exe -s b -l bin -d 'o 4'
complete -c bundle-gem -l no-exe -d 'o 4'
complete -c bundle-gem -l coc -d 'o 4'
complete -c bundle-gem -l no-coc -d 'o 4'
complete -c bundle-gem -l ext -l ext -d 'o 4'
complete -c bundle-gem -l no-ext -d 'o 4'
complete -c bundle-gem -l mit -d 'o 4'
complete -c bundle-gem -l no-mit -d 'o 4'
complete -c bundle-gem -s t -l test -l test -l test -d 'When Bundler is configured to generate tests, this defaults to Bundler\'s glob…'
complete -c bundle-gem -l ci -l ci -l ci -l ci -d 'When Bundler is configured to generate CI files, this defaults to Bundler\'s g…'
complete -c bundle-gem -l linter -l linter -l linter -d 'When Bundler is configured to add a linter, this defaults to Bundler\'s global…'
complete -c bundle-gem -s e -l edit -d ' 0 SEE ALSO o 4 bundle config(1) bundle-config. 1. html  0'

