# bundle
# Autogenerated from man page /usr/share/man/man1/bundle.1.gz
complete -c bundle -l no-color -d 'Print all output without color'
complete -c bundle -l retry -s r -d 'Specify the number of times you wish to attempt network commands'

