# bundle-platform
# Autogenerated from man page /usr/share/man/man1/bundle-platform.1.gz
complete -c bundle-platform -l ruby -d 'It will display the ruby directive information, so you don\'t have to parse it…'

