# bundle-check
# Autogenerated from man page /usr/share/man/man1/bundle-check.1.gz
complete -c bundle-check -l dry-run -d 'Locks the [Gemfile(5)][Gemfile(5)] before running the command'
complete -c bundle-check -l gemfile -d 'Use the specified gemfile instead of the [Gemfile(5)][Gemfile(5)]'

