# bundle-outdated
# Autogenerated from man page /usr/share/man/man1/bundle-outdated.1.gz
complete -c bundle-outdated -l local -d 'Do not attempt to fetch gems remotely and use the gem cache instead'
complete -c bundle-outdated -l pre -d 'Check for newer pre-release gems'
complete -c bundle-outdated -l source -d 'Check against a specific source'
complete -c bundle-outdated -l strict -d 'Only list newer versions allowed by your Gemfile requirements, also respectin…'
complete -c bundle-outdated -l parseable -l porcelain -d 'Use minimal formatting for more parseable output'
complete -c bundle-outdated -l group -d 'List gems from a specific group'
complete -c bundle-outdated -l groups -d 'List gems organized by groups'
complete -c bundle-outdated -l minor -d 'Prefer updating only to next minor version'
complete -c bundle-outdated -l major -d 'Prefer updating to next major version (default)'
complete -c bundle-outdated -l patch -d 'Prefer updating only to next patch version'
complete -c bundle-outdated -l filter-major -d 'Only list major newer versions'
complete -c bundle-outdated -l filter-minor -d 'Only list minor newer versions'
complete -c bundle-outdated -l filter-patch -d 'Only list patch newer versions'

