# bundle-viz
# Autogenerated from man page /usr/share/man/man1/bundle-viz.1.gz
complete -c bundle-viz -l file -s f -d 'The name to use for the generated file.  See --format option'
complete -c bundle-viz -l format -s F -d 'This is output format option.  Supported format is png, jpg, svg, dot \\|. \\|'
complete -c bundle-viz -l requirements -s R -d 'Set to show the version of each required dependency'
complete -c bundle-viz -l version -s v -d 'Set to show each gem version'

