# bundle-remove
# Autogenerated from man page /usr/share/man/man1/bundle-remove.1.gz
complete -c bundle-remove -l install -d 'Runs bundle install after the given gems have been removed from the Gemfile, …'

