# bundle-add
# Autogenerated from man page /usr/share/man/man1/bundle-add.1.gz
complete -c bundle-add -l version -s v -d 'Specify version requirements(s) for the added gem'
complete -c bundle-add -l group -s g -d 'Specify the group(s) for the added gem'
complete -c bundle-add -l source -s s -d 'Specify the source for the added gem'
complete -c bundle-add -l require -s r -d 'Adds require path to gem.  Provide false, or a path as a string'
complete -c bundle-add -l path -d 'Specify the file system path for the added gem'
complete -c bundle-add -l git -d 'Specify the git source for the added gem'
complete -c bundle-add -l github -d 'Specify the github source for the added gem'
complete -c bundle-add -l branch -d 'Specify the git branch for the added gem'
complete -c bundle-add -l ref -d 'Specify the git ref for the added gem'
complete -c bundle-add -l skip-install -d 'Adds the gem to the Gemfile but does not install it'
complete -c bundle-add -l optimistic -d 'Adds optimistic declaration of version'

