# bundle-update
# Autogenerated from man page /usr/share/man/man1/bundle-update.1.gz
complete -c bundle-update -l all -d 'Update all gems specified in Gemfile'
complete -c bundle-update -l group -s g -d 'Only update the gems in the specified group'
complete -c bundle-update -l source -d 'The name of a :git or :path source used in the Gemfile(5)'
complete -c bundle-update -l local -d 'Do not attempt to fetch gems remotely and use the gem cache instead'
complete -c bundle-update -l ruby -d 'Update the locked version of Ruby to the current version of Ruby'
complete -c bundle-update -l bundler -d 'Update the locked version of bundler to the invoked bundler version'
complete -c bundle-update -l full-index -d 'Fall back to using the single-file index of all gems'
complete -c bundle-update -l jobs -s j -d 'Specify the number of jobs to run in parallel'
complete -c bundle-update -l retry -d 'Retry failed network or git requests for number times'
complete -c bundle-update -l quiet -d 'Only output warnings and errors'
complete -c bundle-update -l redownload -d 'Force downloading every gem'
complete -c bundle-update -l patch -d 'Prefer updating only to next patch version'
complete -c bundle-update -l minor -d 'Prefer updating only to next minor version'
complete -c bundle-update -l major -d 'Prefer updating to next major version (default)'
complete -c bundle-update -l strict -d 'Do not allow any gem to be updated past latest --patch | --minor | --major'

