# cd-drive
# Autogenerated from man page /usr/share/man/man1/cd-drive.1.gz
complete -c cd-drive -s d -l debug -d 'Set debugging to LEVEL'
complete -c cd-drive -s i -l cdrom-device -d 'show only info about CD-ROM device'
complete -c cd-drive -s q -l quiet -d 'Don\'t produce warning output'
complete -c cd-drive -s V -l version -d 'display version and copyright information and exit . SS "Help options:"'
complete -c cd-drive -s '?' -l help -d 'Show this help message'
complete -c cd-drive -l usage -d 'Display brief usage message AUTHOR Rocky Bernstein rocky@gnu'

