# cd-info
# Autogenerated from man page /usr/share/man/man1/cd-info.1.gz
complete -c cd-info -s a -l access-mode -d 'Set CD access method'
complete -c cd-info -s d -l debug -d 'Set debugging to LEVEL'
complete -c cd-info -s T -l no-tracks -d 'Don\'t show track information'
complete -c cd-info -s A -l no-analyze -d 'Don\'t show filesystem analysis'
complete -c cd-info -l no-cddb -d 'Does nothing since this program is not'
complete -c cd-info -s P -l cddb-port -d 'CDDB-enabled . HP -H, --cddb-http . HP --cddb-server=\\,STRING\\/ '
complete -c cd-info -l no-device-info -d 'Don\'t show device info, just CD info'
complete -c cd-info -l no-disc-mode -d 'Don\'t show disc-mode info'
complete -c cd-info -l dvd -d 'Attempt to give DVD information if a DVD is found'
complete -c cd-info -s v -l no-vcd -d 'Don\'t look up Video CD information - for this build, this is always set'
complete -c cd-info -s I -l no-ioctl -d 'Don\'t show ioctl() information'
complete -c cd-info -s b -l bin-file -d 'set "bin" CD-ROM disk image file as source'
complete -c cd-info -s c -l cue-file -d 'set "cue" CD-ROM disk image file as source'
complete -c cd-info -s N -l nrg-file -d 'set Nero CD-ROM disk image file as source'
complete -c cd-info -s t -l toc-file -d 'set cdrdao CD-ROM disk image file as source'
complete -c cd-info -s i -l input -d 'set source and determine if "bin" image or device'
complete -c cd-info -l iso9660 -d 'print directory contents of any ISO-9660 filesystems'
complete -c cd-info -s C -l cdrom-device -d 'set CD-ROM device as source'
complete -c cd-info -s l -l list-drives -d 'Give a list of CD-drives'
complete -c cd-info -l no-header -d 'Don\'t display header and copyright (for regression testing)'
complete -c cd-info -l no-joliet -d 'Don\'t use Joliet extensions'
complete -c cd-info -l no-rock-ridge -d 'Don\'t use Rock-Ridge-extension information'
complete -c cd-info -l no-xa -d 'Don\'t use XA-extension information'
complete -c cd-info -s q -l quiet -d 'Don\'t produce warning output'
complete -c cd-info -s V -l version -d 'display version and copyright information and exit . SS "Help options:"'
complete -c cd-info -s '?' -l help -d 'Show this help message'
complete -c cd-info -s H -l cddb-http
complete -c cd-info -l cddb-server
complete -c cd-info -l cddb-cache
complete -c cd-info -l cddb-email
complete -c cd-info -l no-cddb-cache
complete -c cd-info -l cddb-timeout
complete -c cd-info -l usage -d 'Display brief usage message AUTHOR Rocky Bernstein rocky@gnu'

