# chmod
# Autogenerated from man page /usr/share/man/man1/chmod.1.gz
complete -c chmod -s c -l changes -d 'like verbose but report only when a change is made'
complete -c chmod -s f -l silent -l quiet -d 'suppress most error messages'
complete -c chmod -s v -l verbose -d 'output a diagnostic for every file processed'
complete -c chmod -l dereference -d 'affect the referent of each symbolic link, rather than the symbolic link itse…'
complete -c chmod -s h -l no-dereference -d 'affect each symbolic link, rather than the referent'
complete -c chmod -l no-preserve-root -d 'do not treat \'/\' specially (the default)'
complete -c chmod -l preserve-root -d 'fail to operate recursively on \'/\''
complete -c chmod -l reference -d 'use RFILE\'s mode instead of specifying MODE values'
complete -c chmod -s R -l recursive -d 'change files and directories recursively '
complete -c chmod -s H -d 'if a command line argument is a symbolic link to a directory, traverse it'
complete -c chmod -s L -d 'traverse every symbolic link to a directory encountered'
complete -c chmod -s P -d 'do not traverse any symbolic links'
complete -c chmod -l help -d 'display this help and exit'
complete -c chmod -o 6000 -d 'or leading equals like =755 '
complete -c chmod -l version -d 'output version information and exit'

