# cryptsetup-luksAddKey
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksAddKey.8.gz
complete -c cryptsetup-luksAddKey -l new-keyfile -l new-keyfile-offset -l new-keyfile-size -l key-slot
complete -c cryptsetup-luksAddKey -l new-key-slot -l volume-key-file -l volume-key-keyring -l force-password
complete -c cryptsetup-luksAddKey -l hash -l header -l disable-locks -l iter-time -l pbkdf
complete -c cryptsetup-luksAddKey -l pbkdf-force-iterations -l pbkdf-memory -l pbkdf-parallel -l unbound -l type
complete -c cryptsetup-luksAddKey -l keyslot-cipher -l keyslot-key-size -l key-size -l timeout -l token-id
complete -c cryptsetup-luksAddKey -l token-type -l token-only -l new-token-id -l verify-passphrase -l external-tokens-path -d OPTIONS
complete -c cryptsetup-luksAddKey -l batch-mode -s q
complete -c cryptsetup-luksAddKey -l debug -l debug-json
complete -c cryptsetup-luksAddKey -s h
complete -c cryptsetup-luksAddKey -l help -s '?'
complete -c cryptsetup-luksAddKey -s i
complete -c cryptsetup-luksAddKey -l key-file -s d
complete -c cryptsetup-luksAddKey -l keyfile-offset
complete -c cryptsetup-luksAddKey -l keyfile-size -s l
complete -c cryptsetup-luksAddKey -s s
complete -c cryptsetup-luksAddKey -s S
complete -c cryptsetup-luksAddKey -s t
complete -c cryptsetup-luksAddKey -l usage
complete -c cryptsetup-luksAddKey -s y
complete -c cryptsetup-luksAddKey -l version -s V
complete -c cryptsetup-luksAddKey -l master-key-file

