# dbus-broker
# Autogenerated from man page /usr/share/man/man1/dbus-broker.1.gz
complete -c dbus-broker -s h -l help -d 'print usage information and exit immediately'
complete -c dbus-broker -l version -d 'print build-version and exit immediately'
complete -c dbus-broker -l audit -d 'enable logging to the linux audit subsystem (no-op if audit support was not c…'
complete -c dbus-broker -l controller -d 'use the inherited file-descriptor with the given number as the controlling so…'
complete -c dbus-broker -l log -d 'use the inherited file-descriptor with the given number to access the system …'
complete -c dbus-broker -l machine-id -d 'set the machine-id to be advertised by the broker via the org. freedesktop'
complete -c dbus-broker -l max-bytes -d 'maximum number of bytes each user may allocate in the broker (Default: 16 MiB)'
complete -c dbus-broker -l max-fds -d 'maximum number of file descriptors each user may allocate in the broker (Defa…'
complete -c dbus-broker -l max-matches -d 'maximum number of match rules each user may allocate in the broker (Default: …'
complete -c dbus-broker -l max-objects -d 'maximum total number of names, peers, pending replies, etc each user may allo…'

