# dbus-broker-launch
# Autogenerated from man page /usr/share/man/man1/dbus-broker-launch.1.gz
complete -c dbus-broker-launch -s h -l help -d 'print usage information and exit immediately'
complete -c dbus-broker-launch -l version -d 'print build-version and exit immediately'
complete -c dbus-broker-launch -l audit -d 'enable logging to the linux audit subsystem (no-op if audit support was not c…'
complete -c dbus-broker-launch -l config-file -d 'config file to use (Default: /usr/share/dbus-1/{system,session}. conf)'
complete -c dbus-broker-launch -l scope -d 'select scope to run in (one of: system, user; Default: system)'

