# dc1394_vloopback
# Autogenerated from man page /usr/share/man/man1/dc1394_vloopback.1.gz
complete -c dc1394_vloopback -l daemon -d 'run as a daemon, detached from console (optional)'
complete -c dc1394_vloopback -l pipe -d 'write images to vloopback device instead of using zero-copy mmap mode (option…'
complete -c dc1394_vloopback -l guid -d 'select camera to use (optional).  default is first camera on any port'
complete -c dc1394_vloopback -l video1394 -d 'specifies video1394 device to use (optional)'
complete -c dc1394_vloopback -l vloopback -d 'specifies video4linux device to use (optional)'
complete -c dc1394_vloopback -l palette -d 'specify the video palette to use (optional).  yuv422 (default) or rgb24'
complete -c dc1394_vloopback -l width -d 'set the initial width (default=640)'
complete -c dc1394_vloopback -l height -d 'set the initial height (default=480)'
complete -c dc1394_vloopback -l help -d 'print help message'

