# doas
# Autogenerated from man page /usr/share/man/man1/doas.1.gz
complete -c doas -s C -d 'Parse and check the configuration file config, then exit'
complete -c doas -s L -d 'Clear any persisted authentications from previous invocations, then immediate…'
complete -c doas -s n -d 'Non interactive mode, fail if the matching rule doesn\'t have the nopass option'
complete -c doas -s s -d 'Execute the shell from SHELL or /etc/passwd'
complete -c doas -s u -d 'Execute the command as user.  The default is root'

