# enosys
# Autogenerated from man page /usr/share/man/man1/enosys.1.gz
complete -c enosys -s s -l syscall
complete -c enosys -s i -l ioctl
complete -c enosys -s l -l list
complete -c enosys -s m -l list-ioctl
complete -c enosys -s h -l help
complete -c enosys -s V -l version

