# exempi
# Autogenerated from man page /usr/share/man/man1/exempi.1.gz
complete -c exempi -s h
complete -c exempi -s R
complete -c exempi -s x
complete -c exempi -s p
complete -c exempi -s X
complete -c exempi -s w -s s -s o
complete -c exempi -s n
complete -c exempi -s g
complete -c exempi -s v -d '<files> the files to read from'

