# ffmpeg-all
# Autogenerated from man page /usr/share/man/man1/ffmpeg-all.1.gz
complete -c ffmpeg-all -s L -d 'X Item "-L" Show license'
complete -c ffmpeg-all -s h -s '?' -o help -l help -d 'X Item "-h, -?, -help, --help [arg]" Show help'
complete -c ffmpeg-all -o version -d 'X Item "-version" Show version'
complete -c ffmpeg-all -o buildconf -d 'X Item "-buildconf" Show the build configuration, one option per line'
complete -c ffmpeg-all -o formats -d 'X Item "-formats" Show available formats (including devices)'
complete -c ffmpeg-all -o demuxers -d 'X Item "-demuxers" Show available demuxers'
complete -c ffmpeg-all -o muxers -d 'X Item "-muxers" Show available muxers'
complete -c ffmpeg-all -o devices -d 'X Item "-devices" Show available devices'
complete -c ffmpeg-all -o codecs -d 'X Item "-codecs" Show all codecs known to libavcodec'
complete -c ffmpeg-all -o decoders -d 'X Item "-decoders" Show available decoders'
complete -c ffmpeg-all -o encoders -d 'X Item "-encoders" Show all available encoders'
complete -c ffmpeg-all -o bsfs -d 'X Item "-bsfs" Show available bitstream filters'
complete -c ffmpeg-all -o protocols -d 'X Item "-protocols" Show available protocols'
complete -c ffmpeg-all -o filters -d 'X Item "-filters" Show available libavfilter filters'
complete -c ffmpeg-all -o pix_fmts -d 'X Item "-pix_fmts" Show available pixel formats'
complete -c ffmpeg-all -o sample_fmts -d 'X Item "-sample_fmts" Show available sample formats'
complete -c ffmpeg-all -o layouts -d 'X Item "-layouts" Show channel names and standard channel layouts'
complete -c ffmpeg-all -o dispositions -d 'X Item "-dispositions" Show stream dispositions'
complete -c ffmpeg-all -o colors -d 'X Item "-colors" Show recognized color names'
complete -c ffmpeg-all -o sources -d 'X Item "-sources device[,opt1=val1[,opt2=val2]'
complete -c ffmpeg-all -o sinks -d 'X Item "-sinks device[,opt1=val1[,opt2=val2]'
complete -c ffmpeg-all -o loglevel -s v -d 'X Item "-loglevel [flags+]loglevel | -v [flags+]loglevel" Set logging level a…'
complete -c ffmpeg-all -s 8 -d 'X Item "quiet, -8" Show nothing at all; be silent'
complete -c ffmpeg-all -o report -d 'X Item "-report" Dump full command line and log output to a file named \\f(CW\\…'
complete -c ffmpeg-all -o hide_banner -d 'X Item "-hide_banner" Suppress printing banner'
complete -c ffmpeg-all -o cpuflags -d 'X Item "-cpuflags flags (global)" Allows setting and clearing cpu flags'
complete -c ffmpeg-all -o cpucount -d 'X Item "-cpucount count (global)" . PD Override detection of CPU count'
complete -c ffmpeg-all -o max_alloc -d 'X Item "-max_alloc bytes" Set the maximum size limit for allocating a block o…'
complete -c ffmpeg-all -s f -d 'X Item "-f fmt (input/output)" Force input or output file format'
complete -c ffmpeg-all -s i -d 'X Item "-i url (input)" input file url'
complete -c ffmpeg-all -s y -d 'X Item "-y (global)" Overwrite output files without asking'
complete -c ffmpeg-all -s n -d 'X Item "-n (global)" Do not overwrite output files, and exit immediately if a…'
complete -c ffmpeg-all -o stream_loop -d 'X Item "-stream_loop number (input)" Set number of times input stream shall b…'
complete -c ffmpeg-all -o recast_media -d 'X Item "-recast_media (global)" Allow forcing a decoder of a different media …'
complete -c ffmpeg-all -s c -d 'X Item "-c[:stream_specifier] codec (input/output,per-stream)"'
complete -c ffmpeg-all -o codec -d 'X Item "-codec[:stream_specifier] codec (input/output,per-stream)" '
complete -c ffmpeg-all -s t -d 'X Item "-t duration (input/output)" When used as an input option (before \\f(C…'
complete -c ffmpeg-all -o to -d 'X Item "-to position (input/output)" Stop writing the output or reading the i…'
complete -c ffmpeg-all -o fs -d 'X Item "-fs limit_size (output)" Set the file size limit, expressed in bytes'
complete -c ffmpeg-all -o ss -d 'X Item "-ss position (input/output)" When used as an input option (before \\f(…'
complete -c ffmpeg-all -o sseof -d 'X Item "-sseof position (input)" Like the \\f(CW\\*(C`-ss\\*(C\' option but relat…'
complete -c ffmpeg-all -o isync -d 'X Item "-isync input_index (input)" Assign an input as a sync source'
complete -c ffmpeg-all -o itsoffset -d 'X Item "-itsoffset offset (input)" Set the input time offset'
complete -c ffmpeg-all -o itsscale -d 'X Item "-itsscale scale (input,per-stream)" Rescale input timestamps'
complete -c ffmpeg-all -o timestamp -d 'X Item "-timestamp date (output)" Set the recording timestamp in the container'
complete -c ffmpeg-all -o metadata -d 'X Item "-metadata[:metadata_specifier] key=value (output,per-metadata)" Set a…'
complete -c ffmpeg-all -o disposition -d 'X Item "-disposition[:stream_specifier] value (output,per-stream)" Sets the d…'
complete -c ffmpeg-all -o program -d 'X Item "-program [title=title:][program_num=program_num:]st=stream[:st=stream'
complete -c ffmpeg-all -o target -d 'X Item "-target type (output)" Specify target file type (\\f(CW\\*(C`vcd\\*(C\', …'
complete -c ffmpeg-all -o dn -d 'X Item "-dn (input/output)" As an input option, blocks all data streams of a …'
complete -c ffmpeg-all -o dframes -d 'X Item "-dframes number (output)" Set the number of data frames to output'
complete -c ffmpeg-all -o frames -d 'X Item "-frames[:stream_specifier] framecount (output,per-stream)" Stop writi…'
complete -c ffmpeg-all -s q -d 'X Item "-q[:stream_specifier] q (output,per-stream)"'
complete -c ffmpeg-all -o qscale -d 'X Item "-qscale[:stream_specifier] q (output,per-stream)" '
complete -c ffmpeg-all -o filter -d 'X Item "-filter[:stream_specifier] filtergraph (output,per-stream)" Create th…'
complete -c ffmpeg-all -o filter_script -d 'X Item "-filter_script[:stream_specifier] filename (output,per-stream)" This …'
complete -c ffmpeg-all -o reinit_filter -d 'X Item "-reinit_filter[:stream_specifier] integer (input,per-stream)" This bo…'
complete -c ffmpeg-all -o filter_threads -d 'X Item "-filter_threads nb_threads (global)" Defines how many threads are use…'
complete -c ffmpeg-all -o pre -d 'X Item "-pre[:stream_specifier] preset_name (output,per-stream)" Specify the …'
complete -c ffmpeg-all -o stats -d 'X Item "-stats (global)" Print encoding progress/statistics'
complete -c ffmpeg-all -o stats_period -d 'X Item "-stats_period time (global)" Set period at which encoding progress/st…'
complete -c ffmpeg-all -o progress -d 'X Item "-progress url (global)" Send program-friendly progress information to…'
complete -c ffmpeg-all -o stdin -d 'X Item "-stdin" Enable interaction on standard input'
complete -c ffmpeg-all -o debug_ts -d 'X Item "-debug_ts (global)" Print timestamp information'
complete -c ffmpeg-all -o attach -d 'X Item "-attach filename (output)" Add an attachment to the output file'
complete -c ffmpeg-all -o dump_attachment -d 'X Item "-dump_attachment[:stream_specifier] filename (input,per-stream)" Extr…'
complete -c ffmpeg-all -o vframes -d 'X Item "-vframes number (output)" Set the number of video frames to output'
complete -c ffmpeg-all -s r -d 'X Item "-r[:stream_specifier] fps (input/output,per-stream)" Set frame rate (…'
complete -c ffmpeg-all -o fpsmax -d 'X Item "-fpsmax[:stream_specifier] fps (output,per-stream)" Set maximum frame…'
complete -c ffmpeg-all -s s -d 'X Item "-s[:stream_specifier] size (input/output,per-stream)" Set frame size'
complete -c ffmpeg-all -o aspect -d 'X Item "-aspect[:stream_specifier] aspect (output,per-stream)" Set the video …'
complete -c ffmpeg-all -o display_rotation -d 'X Item "-display_rotation[:stream_specifier] rotation (input,per-stream)" Set…'
complete -c ffmpeg-all -o display_hflip -d 'X Item "-display_hflip[:stream_specifier] (input,per-stream)" Set whether on …'
complete -c ffmpeg-all -o display_vflip -d 'X Item "-display_vflip[:stream_specifier] (input,per-stream)" Set whether on …'
complete -c ffmpeg-all -o vn -d 'X Item "-vn (input/output)" As an input option, blocks all video streams of a…'
complete -c ffmpeg-all -o vcodec -d 'X Item "-vcodec codec (output)" Set the video codec'
complete -c ffmpeg-all -o pass -d 'X Item "-pass[:stream_specifier] n (output,per-stream)" Select the pass numbe…'
complete -c ffmpeg-all -o passlogfile -d 'X Item "-passlogfile[:stream_specifier] prefix (output,per-stream)" Set two-p…'
complete -c ffmpeg-all -o vf -d 'X Item "-vf filtergraph (output)" Create the filtergraph specified by filterg…'
complete -c ffmpeg-all -o autorotate -d 'X Item "-autorotate" Automatically rotate the video according to file metadata'
complete -c ffmpeg-all -o autoscale -d 'X Item "-autoscale" Automatically scale the video according to the resolution…'
complete -c ffmpeg-all -o pix_fmt -d 'X Item "-pix_fmt[:stream_specifier] format (input/output,per-stream)" Set pix…'
complete -c ffmpeg-all -o sws_flags -d 'X Item "-sws_flags flags (input/output)" Set default flags for the libswscale…'
complete -c ffmpeg-all -o rc_override -d 'X Item "-rc_override[:stream_specifier] override (output,per-stream)" Rate co…'
complete -c ffmpeg-all -o psnr -d 'X Item "-psnr" Calculate PSNR of compressed frames'
complete -c ffmpeg-all -o vstats -d 'X Item "-vstats" Dump video coding statistics to vstats_HHMMSS. log'
complete -c ffmpeg-all -o vstats_file -d 'X Item "-vstats_file file" Dump video coding statistics to file'
complete -c ffmpeg-all -o vstats_version -d 'X Item "-vstats_version file" Specify which version of the vstats format to u…'
complete -c ffmpeg-all -o vtag -d 'X Item "-vtag fourcc/tag (output)" Force video tag/fourcc'
complete -c ffmpeg-all -o vbsf -d 'X Item "-vbsf bitstream_filter" Deprecated see -bsf'
complete -c ffmpeg-all -o force_key_frames -d 'X Item "-force_key_frames[:stream_specifier] time[,time'
complete -c ffmpeg-all -o copyinkf -d 'X Item "-copyinkf[:stream_specifier] (output,per-stream)" When doing stream c…'
complete -c ffmpeg-all -o init_hw_device -d 'X Item "-init_hw_device type[=name][:device[,key=value'
complete -c ffmpeg-all -o filter_hw_device -d 'X Item "-filter_hw_device name" Pass the hardware device called name to all f…'
complete -c ffmpeg-all -o hwaccel -d 'X Item "-hwaccel[:stream_specifier] hwaccel (input,per-stream)" Use hardware …'
complete -c ffmpeg-all -o hwaccel_device -d 'X Item "-hwaccel_device[:stream_specifier] hwaccel_device (input,per-stream)"…'
complete -c ffmpeg-all -o hwaccels -d 'X Item "-hwaccels" List all hardware acceleration components enabled in this …'
complete -c ffmpeg-all -o fix_sub_duration_heartbeat -d 'X Item "-fix_sub_duration_heartbeat[:stream_specifier]" Set a specific output…'
complete -c ffmpeg-all -o aframes -d 'X Item "-aframes number (output)" Set the number of audio frames to output'
complete -c ffmpeg-all -o ar -d 'X Item "-ar[:stream_specifier] freq (input/output,per-stream)" Set the audio …'
complete -c ffmpeg-all -o aq -d 'X Item "-aq q (output)" Set the audio quality (codec-specific, VBR)'
complete -c ffmpeg-all -o ac -d 'X Item "-ac[:stream_specifier] channels (input/output,per-stream)" Set the nu…'
complete -c ffmpeg-all -o an -d 'X Item "-an (input/output)" As an input option, blocks all audio streams of a…'
complete -c ffmpeg-all -o acodec -d 'X Item "-acodec codec (input/output)" Set the audio codec'
complete -c ffmpeg-all -o sample_fmt -d 'X Item "-sample_fmt[:stream_specifier] sample_fmt (output,per-stream)" Set th…'
complete -c ffmpeg-all -o af -d 'X Item "-af filtergraph (output)" Create the filtergraph specified by filterg…'
complete -c ffmpeg-all -o atag -d 'X Item "-atag fourcc/tag (output)" Force audio tag/fourcc'
complete -c ffmpeg-all -o absf -d 'X Item "-absf bitstream_filter" Deprecated, see -bsf'
complete -c ffmpeg-all -o guess_layout_max -d 'X Item "-guess_layout_max channels (input,per-stream)" If some input channel …'
complete -c ffmpeg-all -o scodec -d 'X Item "-scodec codec (input/output)" Set the subtitle codec'
complete -c ffmpeg-all -o sn -d 'X Item "-sn (input/output)" As an input option, blocks all subtitle streams o…'
complete -c ffmpeg-all -o sbsf -d 'X Item "-sbsf bitstream_filter" Deprecated, see -bsf '
complete -c ffmpeg-all -o fix_sub_duration -d 'X Item "-fix_sub_duration" Fix subtitles durations'
complete -c ffmpeg-all -o canvas_size -d 'X Item "-canvas_size size" Set the size of the canvas used to render subtitles'
complete -c ffmpeg-all -o map -d 'X Item "-map [-]input_file_id[:stream_specifier][?] | [linklabel] (output)" C…'
complete -c ffmpeg-all -o ignore_unknown -d 'X Item "-ignore_unknown" Ignore input streams with unknown type instead of fa…'
complete -c ffmpeg-all -o copy_unknown -d 'X Item "-copy_unknown" Allow input streams with unknown type to be copied ins…'
complete -c ffmpeg-all -o map_channel -s 1 -d 'X Item "-map_channel [input_file_id. stream_specifier'
complete -c ffmpeg-all -o map_metadata -d 'X Item "-map_metadata[:metadata_spec_out] infile[:metadata_spec_in] (output,p…'
complete -c ffmpeg-all -o map_chapters -d 'X Item "-map_chapters input_file_index (output)" Copy chapters from input fil…'
complete -c ffmpeg-all -o benchmark -d 'X Item "-benchmark (global)" Show benchmarking information at the end of an e…'
complete -c ffmpeg-all -o benchmark_all -d 'X Item "-benchmark_all (global)" Show benchmarking information during the enc…'
complete -c ffmpeg-all -o timelimit -d 'X Item "-timelimit duration (global)" Exit after ffmpeg has been running for …'
complete -c ffmpeg-all -o dump -d 'X Item "-dump (global)" Dump each input packet to stderr'
complete -c ffmpeg-all -o hex -d 'X Item "-hex (global)" When dumping packets, also dump the payload'
complete -c ffmpeg-all -o readrate -d 'X Item "-readrate speed (input)" Limit input read speed'
complete -c ffmpeg-all -o re -d 'X Item "-re (input)" Read input at native frame rate'
complete -c ffmpeg-all -o readrate_initial_burst -d 'X Item "-readrate_initial_burst seconds" Set an initial read burst time, in s…'
complete -c ffmpeg-all -o vsync -d 'X Item "-vsync parameter (global)"'
complete -c ffmpeg-all -o fps_mode -d 'X Item "-fps_mode[:stream_specifier] parameter (output,per-stream)" '
complete -c ffmpeg-all -o frame_drop_threshold -d 'X Item "-frame_drop_threshold parameter" Frame drop threshold, which specifie…'
complete -c ffmpeg-all -o apad -d 'X Item "-apad parameters (output,per-stream)" Pad the output audio stream(s)'
complete -c ffmpeg-all -o copyts -d 'X Item "-copyts" Do not process input timestamps, but keep their values witho…'
complete -c ffmpeg-all -o start_at_zero -d 'X Item "-start_at_zero" When used with copyts, shift input timestamps so they…'
complete -c ffmpeg-all -o copytb -d 'X Item "-copytb mode" Specify how to set the encoder timebase when stream cop…'
complete -c ffmpeg-all -o enc_time_base -d 'X Item "-enc_time_base[:stream_specifier] timebase (output,per-stream)" Set t…'
complete -c ffmpeg-all -o bitexact -d 'X Item "-bitexact (input/output)" Enable bitexact mode for (de)muxer and (de/…'
complete -c ffmpeg-all -o shortest -d 'X Item "-shortest (output)" Finish encoding when the shortest output stream e…'
complete -c ffmpeg-all -o shortest_buf_duration -d 'X Item "-shortest_buf_duration duration (output)" The \\f(CW\\*(C`-shortest\\*(C…'
complete -c ffmpeg-all -o dts_delta_threshold -d 'X Item "-dts_delta_threshold threshold" Timestamp discontinuity delta thresho…'
complete -c ffmpeg-all -o dts_error_threshold -d 'X Item "-dts_error_threshold threshold" Timestamp error delta threshold, expr…'
complete -c ffmpeg-all -o muxdelay -d 'X Item "-muxdelay seconds (output)" Set the maximum demux-decode delay'
complete -c ffmpeg-all -o muxpreload -d 'X Item "-muxpreload seconds (output)" Set the initial demux-decode delay'
complete -c ffmpeg-all -o streamid -d 'X Item "-streamid output-stream-index:new-value (output)" Assign a new stream…'
complete -c ffmpeg-all -o bsf -d 'X Item "-bsf[:stream_specifier] bitstream_filters (output,per-stream)" Set bi…'
complete -c ffmpeg-all -o tag -d 'X Item "-tag[:stream_specifier] codec_tag (input/output,per-stream)" Force a …'
complete -c ffmpeg-all -o timecode -d 'X Item "-timecode hh:mm:ssSEPff" Specify Timecode for writing'
complete -c ffmpeg-all -o filter_complex -d 'X Item "-filter_complex filtergraph (global)" Define a complex filtergraph, i'
complete -c ffmpeg-all -o filter_complex_threads -d 'X Item "-filter_complex_threads nb_threads (global)" Defines how many threads…'
complete -c ffmpeg-all -o lavfi -d 'X Item "-lavfi filtergraph (global)" Define a complex filtergraph, i. e'
complete -c ffmpeg-all -o filter_complex_script -d 'X Item "-filter_complex_script filename (global)" This option is similar to -…'
complete -c ffmpeg-all -o accurate_seek -d 'X Item "-accurate_seek (input)" This option enables or disables accurate seek…'
complete -c ffmpeg-all -o seek_timestamp -d 'X Item "-seek_timestamp (input)" This option enables or disables seeking by t…'
complete -c ffmpeg-all -o thread_queue_size -d 'X Item "-thread_queue_size size (input/output)" For input, this option sets t…'
complete -c ffmpeg-all -o sdp_file -d 'X Item "-sdp_file file (global)" Print sdp information for an output stream t…'
complete -c ffmpeg-all -o discard -d 'X Item "-discard (input)" Allows discarding specific streams or frames from s…'
complete -c ffmpeg-all -o abort_on -d 'X Item "-abort_on flags (global)" Stop and abort on various conditions'
complete -c ffmpeg-all -o max_error_rate -d 'X Item "-max_error_rate (global)" Set fraction of decoding frame failures acr…'
complete -c ffmpeg-all -o xerror -d 'X Item "-xerror (global)" Stop and exit on error'
complete -c ffmpeg-all -o max_muxing_queue_size -d 'X Item "-max_muxing_queue_size packets (output,per-stream)" When transcoding …'
complete -c ffmpeg-all -o muxing_queue_data_threshold -d 'X Item "-muxing_queue_data_threshold bytes (output,per-stream)" This is a min…'
complete -c ffmpeg-all -o auto_conversion_filters -d 'X Item "-auto_conversion_filters (global)" Enable automatically inserting for…'
complete -c ffmpeg-all -o bits_per_raw_sample -d 'X Item "-bits_per_raw_sample[:stream_specifier] value (output,per-stream)" De…'
complete -c ffmpeg-all -o stats_enc_pre -d 'X Item "-stats_enc_pre[:stream_specifier] path (output,per-stream)"'
complete -c ffmpeg-all -o stats_enc_post -d 'X Item "-stats_enc_post[:stream_specifier] path (output,per-stream)"'
complete -c ffmpeg-all -o stats_mux_pre -d 'X Item "-stats_mux_pre[:stream_specifier] path (output,per-stream)" '
complete -c ffmpeg-all -o stats_enc_pre_fmt -d 'X Item "-stats_enc_pre_fmt[:stream_specifier] format_spec (output,per-stream)"'
complete -c ffmpeg-all -o stats_enc_post_fmt -d 'X Item "-stats_enc_post_fmt[:stream_specifier] format_spec (output,per-stream…'
complete -c ffmpeg-all -o stats_mux_pre_fmt -d 'X Item "-stats_mux_pre_fmt[:stream_specifier] format_spec (output,per-stream)…'
complete -c ffmpeg-all -o drc_scale
complete -c ffmpeg-all -o use_buggy_lpc
complete -c ffmpeg-all -o aribb24-base-path
complete -c ffmpeg-all -o aribb24-skip-ruby-text
complete -c ffmpeg-all -o sub_type
complete -c ffmpeg-all -o caption_encoding
complete -c ffmpeg-all -o font
complete -c ffmpeg-all -o ass_single_rect
complete -c ffmpeg-all -o force_outline_text
complete -c ffmpeg-all -o outline_width
complete -c ffmpeg-all -o ignore_background
complete -c ffmpeg-all -o ignore_ruby
complete -c ffmpeg-all -o replace_drcs
complete -c ffmpeg-all -o replace_msz_ascii
complete -c ffmpeg-all -o replace_msz_japanese
complete -c ffmpeg-all -o replace_msz_glyph
complete -c ffmpeg-all -s 2 -d 'Compute clut once if no matching CLUT is in the stream'
complete -c ffmpeg-all -o per_frame_metadata
complete -c ffmpeg-all -o center_mixlev
complete -c ffmpeg-all -o surround_mixlev
complete -c ffmpeg-all -o mixing_level
complete -c ffmpeg-all -o room_type
complete -c ffmpeg-all -o copyright
complete -c ffmpeg-all -o dialnorm
complete -c ffmpeg-all -o dsur_mode
complete -c ffmpeg-all -o original
complete -c ffmpeg-all -o dmix_mode
complete -c ffmpeg-all -o ltrt_cmixlev
complete -c ffmpeg-all -o ltrt_surmixlev
complete -c ffmpeg-all -o loro_cmixlev
complete -c ffmpeg-all -o loro_surmixlev
complete -c ffmpeg-all -o dsurex_mode
complete -c ffmpeg-all -o dheadphone_mode
complete -c ffmpeg-all -o ad_conv_type
complete -c ffmpeg-all -o stereo_rematrixing
complete -c ffmpeg-all -o channel_coupling
complete -c ffmpeg-all -o cpl_start_band
complete -c ffmpeg-all -l nores -d 'joint_stereo (-m j) 4'
complete -c ffmpeg-all -l abr -d 'tells FFmpeg to use ABR still relies on b to set bitrate.  copyright (-c) 4'
complete -c ffmpeg-all -o '15.0' -d 'to the crispness of transients in the encoded audio'
complete -c ffmpeg-all -l enable-libkvazaar
complete -c ffmpeg-all -o lossless
complete -c ffmpeg-all -o compression_level
complete -c ffmpeg-all -o quality
complete -c ffmpeg-all -o preset
complete -c ffmpeg-all -l slow-firstpass -d 'crf (crf) 4'
complete -c ffmpeg-all -l no-fast-pskip -d 'aud (aud) 4'
complete -c ffmpeg-all -l no-mbtree -d 'deblock (deblock) 4'
complete -c ffmpeg-all -l enable-libx265
complete -c ffmpeg-all -l enable-libxavs2
complete -c ffmpeg-all -o tag:v
complete -c ffmpeg-all -o ignore_loop
complete -c ffmpeg-all -o max_fps
complete -c ffmpeg-all -o default_fps
complete -c ffmpeg-all -o no_resync_search
complete -c ffmpeg-all -o flv_metadata
complete -c ffmpeg-all -o flv_ignore_prevtag
complete -c ffmpeg-all -o flv_full_metadata
complete -c ffmpeg-all -o hls_enc
complete -c ffmpeg-all -o hls_enc_key
complete -c ffmpeg-all -o hls_enc_key_url
complete -c ffmpeg-all -o hls_enc_iv
complete -c ffmpeg-all -o syncpoints
complete -c ffmpeg-all -o write_index
complete -c ffmpeg-all -o page_duration
complete -c ffmpeg-all -o serial_offset
complete -c ffmpeg-all -o list_devices
complete -c ffmpeg-all -o video_device_index
complete -c ffmpeg-all -o audio_device_index
complete -c ffmpeg-all -o pixel_format
complete -c ffmpeg-all -o framerate
complete -c ffmpeg-all -o video_size
complete -c ffmpeg-all -o capture_cursor
complete -c ffmpeg-all -o capture_mouse_clicks
complete -c ffmpeg-all -o capture_raw_data
complete -c ffmpeg-all -o list_formats -d 'of channels can be 2, 8 or 16'
complete -c ffmpeg-all -o timestamps -o ts -d 'conversion into the real time clock'
complete -c ffmpeg-all -o root
complete -c ffmpeg-all -o filter/-vf/-af
complete -c ffmpeg-all -o vf/-af -d 'avfilter_graph_parse_ptr() function defined in libavfilter/avfilter. h'
complete -c ffmpeg-all -o '1.0' -d 'audio signal, or "waveform", should be centered around the zero point'
complete -c ffmpeg-all -o 12 -o 1/10 -d 'this region should be encoded with a QP around one-tenth of the full range be…'
complete -c ffmpeg-all -o '1000.0' -d 'brightness 4'
complete -c ffmpeg-all -o 100 -o '0.743643887037158704752191506114774' -d 'start_y 4'
complete -c ffmpeg-all -o '0.131825904205311970493132056385139' -d mptestsrc

