# ffmpeg-codecs
# Autogenerated from man page /usr/share/man/man1/ffmpeg-codecs.1.gz
complete -c ffmpeg-codecs -s 1
complete -c ffmpeg-codecs -o drc_scale
complete -c ffmpeg-codecs -o use_buggy_lpc
complete -c ffmpeg-codecs -o aribb24-base-path
complete -c ffmpeg-codecs -o aribb24-skip-ruby-text
complete -c ffmpeg-codecs -o sub_type
complete -c ffmpeg-codecs -o caption_encoding
complete -c ffmpeg-codecs -o font
complete -c ffmpeg-codecs -o ass_single_rect
complete -c ffmpeg-codecs -o force_outline_text
complete -c ffmpeg-codecs -o outline_width
complete -c ffmpeg-codecs -o ignore_background
complete -c ffmpeg-codecs -o ignore_ruby
complete -c ffmpeg-codecs -o replace_drcs
complete -c ffmpeg-codecs -o replace_msz_ascii
complete -c ffmpeg-codecs -o replace_msz_japanese
complete -c ffmpeg-codecs -o replace_msz_glyph
complete -c ffmpeg-codecs -o canvas_size
complete -c ffmpeg-codecs -s 2 -d 'Compute clut once if no matching CLUT is in the stream'
complete -c ffmpeg-codecs -o per_frame_metadata
complete -c ffmpeg-codecs -o center_mixlev
complete -c ffmpeg-codecs -o surround_mixlev
complete -c ffmpeg-codecs -o mixing_level
complete -c ffmpeg-codecs -o room_type
complete -c ffmpeg-codecs -o copyright
complete -c ffmpeg-codecs -o dialnorm
complete -c ffmpeg-codecs -o dsur_mode
complete -c ffmpeg-codecs -o original
complete -c ffmpeg-codecs -o dmix_mode
complete -c ffmpeg-codecs -o ltrt_cmixlev
complete -c ffmpeg-codecs -o ltrt_surmixlev
complete -c ffmpeg-codecs -o loro_cmixlev
complete -c ffmpeg-codecs -o loro_surmixlev
complete -c ffmpeg-codecs -o dsurex_mode
complete -c ffmpeg-codecs -o dheadphone_mode
complete -c ffmpeg-codecs -o ad_conv_type
complete -c ffmpeg-codecs -o stereo_rematrixing
complete -c ffmpeg-codecs -o channel_coupling
complete -c ffmpeg-codecs -o cpl_start_band
complete -c ffmpeg-codecs -l nores -d 'joint_stereo (-m j) 4'
complete -c ffmpeg-codecs -l abr -d 'tells FFmpeg to use ABR still relies on b to set bitrate.  copyright (-c) 4'
complete -c ffmpeg-codecs -o '15.0' -d 'to the crispness of transients in the encoded audio'
complete -c ffmpeg-codecs -l enable-libkvazaar
complete -c ffmpeg-codecs -o lossless
complete -c ffmpeg-codecs -o compression_level
complete -c ffmpeg-codecs -o quality
complete -c ffmpeg-codecs -o preset
complete -c ffmpeg-codecs -l slow-firstpass -d 'crf (crf) 4'
complete -c ffmpeg-codecs -l no-fast-pskip -d 'aud (aud) 4'
complete -c ffmpeg-codecs -l no-mbtree -d 'deblock (deblock) 4'
complete -c ffmpeg-codecs -l enable-libx265
complete -c ffmpeg-codecs -l enable-libxavs2

