# ffmpeg-devices
# Autogenerated from man page /usr/share/man/man1/ffmpeg-devices.1.gz
complete -c ffmpeg-devices -o list_devices
complete -c ffmpeg-devices -o video_device_index
complete -c ffmpeg-devices -o audio_device_index
complete -c ffmpeg-devices -o pixel_format
complete -c ffmpeg-devices -o framerate
complete -c ffmpeg-devices -o video_size
complete -c ffmpeg-devices -o capture_cursor
complete -c ffmpeg-devices -o capture_mouse_clicks
complete -c ffmpeg-devices -o capture_raw_data
complete -c ffmpeg-devices -o list_formats -d 'of channels can be 2, 8 or 16'
complete -c ffmpeg-devices -o timestamps -o ts -d 'conversion into the real time clock'
complete -c ffmpeg-devices -o root

