# ffmpeg-filters
# Autogenerated from man page /usr/share/man/man1/ffmpeg-filters.1.gz
complete -c ffmpeg-filters -o filter/-vf/-af
complete -c ffmpeg-filters -o filter_complex
complete -c ffmpeg-filters -o vf/-af -d 'avfilter_graph_parse_ptr() function defined in libavfilter/avfilter. h'
complete -c ffmpeg-filters -o filter_script
complete -c ffmpeg-filters -o filter_complex_script -d 'TIMELINE EDITING'
complete -c ffmpeg-filters -o '1.0' -d 'audio signal, or "waveform", should be centered around the zero point'
complete -c ffmpeg-filters -o 12 -o 1/10 -d 'this region should be encoded with a QP around one-tenth of the full range be…'
complete -c ffmpeg-filters -s 1
complete -c ffmpeg-filters -o '1000.0' -d 'brightness 4'
complete -c ffmpeg-filters -o init_hw_device
complete -c ffmpeg-filters -o filter_hw_device
complete -c ffmpeg-filters -o 100 -o '0.743643887037158704752191506114774' -d 'start_y 4'
complete -c ffmpeg-filters -o '0.131825904205311970493132056385139' -d mptestsrc

