# ffplay-all
# Autogenerated from man page /usr/share/man/man1/ffplay-all.1.gz
complete -c ffplay-all -s L -d 'X Item "-L" Show license'
complete -c ffplay-all -s h -s '?' -o help -l help -d 'X Item "-h, -?, -help, --help [arg]" Show help'
complete -c ffplay-all -o version -d 'X Item "-version" Show version'
complete -c ffplay-all -o buildconf -d 'X Item "-buildconf" Show the build configuration, one option per line'
complete -c ffplay-all -o formats -d 'X Item "-formats" Show available formats (including devices)'
complete -c ffplay-all -o demuxers -d 'X Item "-demuxers" Show available demuxers'
complete -c ffplay-all -o muxers -d 'X Item "-muxers" Show available muxers'
complete -c ffplay-all -o devices -d 'X Item "-devices" Show available devices'
complete -c ffplay-all -o codecs -d 'X Item "-codecs" Show all codecs known to libavcodec'
complete -c ffplay-all -o decoders -d 'X Item "-decoders" Show available decoders'
complete -c ffplay-all -o encoders -d 'X Item "-encoders" Show all available encoders'
complete -c ffplay-all -o bsfs -d 'X Item "-bsfs" Show available bitstream filters'
complete -c ffplay-all -o protocols -d 'X Item "-protocols" Show available protocols'
complete -c ffplay-all -o filters -d 'X Item "-filters" Show available libavfilter filters'
complete -c ffplay-all -o pix_fmts -d 'X Item "-pix_fmts" Show available pixel formats'
complete -c ffplay-all -o sample_fmts -d 'X Item "-sample_fmts" Show available sample formats'
complete -c ffplay-all -o layouts -d 'X Item "-layouts" Show channel names and standard channel layouts'
complete -c ffplay-all -o dispositions -d 'X Item "-dispositions" Show stream dispositions'
complete -c ffplay-all -o colors -d 'X Item "-colors" Show recognized color names'
complete -c ffplay-all -o sources -d 'X Item "-sources device[,opt1=val1[,opt2=val2]'
complete -c ffplay-all -o sinks -d 'X Item "-sinks device[,opt1=val1[,opt2=val2]'
complete -c ffplay-all -o loglevel -s v -d 'X Item "-loglevel [flags+]loglevel | -v [flags+]loglevel" Set logging level a…'
complete -c ffplay-all -s 8 -d 'X Item "quiet, -8" Show nothing at all; be silent'
complete -c ffplay-all -o report -d 'X Item "-report" Dump full command line and log output to a file named \\f(CW\\…'
complete -c ffplay-all -o hide_banner -d 'X Item "-hide_banner" Suppress printing banner'
complete -c ffplay-all -o cpuflags -d 'X Item "-cpuflags flags (global)" Allows setting and clearing cpu flags'
complete -c ffplay-all -o cpucount -d 'X Item "-cpucount count (global)" . PD Override detection of CPU count'
complete -c ffplay-all -o max_alloc -d 'X Item "-max_alloc bytes" Set the maximum size limit for allocating a block o…'
complete -c ffplay-all -s x -d 'X Item "-x width" Force displayed width'
complete -c ffplay-all -s y -d 'X Item "-y height" Force displayed height'
complete -c ffplay-all -o fs -d 'X Item "-fs" Start in fullscreen mode'
complete -c ffplay-all -o an -d 'X Item "-an" Disable audio'
complete -c ffplay-all -o vn -d 'X Item "-vn" Disable video'
complete -c ffplay-all -o sn -d 'X Item "-sn" Disable subtitles'
complete -c ffplay-all -o ss -d 'X Item "-ss pos" Seek to pos'
complete -c ffplay-all -s t -d 'X Item "-t duration" Play duration seconds of audio/video'
complete -c ffplay-all -o bytes -d 'X Item "-bytes" Seek by bytes'
complete -c ffplay-all -o seek_interval -d 'X Item "-seek_interval" Set custom interval, in seconds, for seeking using le…'
complete -c ffplay-all -o nodisp -d 'X Item "-nodisp" Disable graphical display'
complete -c ffplay-all -o noborder -d 'X Item "-noborder" Borderless window'
complete -c ffplay-all -o alwaysontop -d 'X Item "-alwaysontop" Window always on top.  Available on: X11 with SDL >= 2'
complete -c ffplay-all -o volume -d 'X Item "-volume" Set the startup volume'
complete -c ffplay-all -s f -d 'X Item "-f fmt" Force format'
complete -c ffplay-all -o window_title -d 'X Item "-window_title title" Set window title (default is the input filename)'
complete -c ffplay-all -o left -d 'X Item "-left title" Set the x position for the left of the window (default i…'
complete -c ffplay-all -o top -d 'X Item "-top title" Set the y position for the top of the window (default is …'
complete -c ffplay-all -o loop -d 'X Item "-loop number" Loops movie playback <number> times.  0 means forever'
complete -c ffplay-all -o showmode -d 'X Item "-showmode mode" Set the show mode to use'
complete -c ffplay-all -o vf -d 'X Item "-vf filtergraph" Create the filtergraph specified by filtergraph and …'
complete -c ffplay-all -o af -d 'X Item "-af filtergraph" filtergraph is a description of the filtergraph to a…'
complete -c ffplay-all -s i -d 'X Item "-i input_url" Read input_url'
complete -c ffplay-all -o stats -d 'X Item "-stats" Print several playback statistics, in particular show the str…'
complete -c ffplay-all -o fast -d 'X Item "-fast" Non-spec-compliant optimizations'
complete -c ffplay-all -o genpts -d 'X Item "-genpts" Generate pts'
complete -c ffplay-all -o sync -d 'X Item "-sync type" Set the master clock to audio (\\f(CW\\*(C`type=audio\\*(C\')…'
complete -c ffplay-all -o ast -d 'X Item "-ast audio_stream_specifier" Select the desired audio stream using th…'
complete -c ffplay-all -o vst -d 'X Item "-vst video_stream_specifier" Select the desired video stream using th…'
complete -c ffplay-all -o sst -d 'X Item "-sst subtitle_stream_specifier" Select the desired subtitle stream us…'
complete -c ffplay-all -o autoexit -d 'X Item "-autoexit" Exit when video is done playing'
complete -c ffplay-all -o exitonkeydown -d 'X Item "-exitonkeydown" Exit if any key is pressed'
complete -c ffplay-all -o exitonmousedown -d 'X Item "-exitonmousedown" Exit if any mouse button is pressed'
complete -c ffplay-all -o codec:media_specifier -d 'X Item "-codec:media_specifier codec_name" Force a specific decoder implement…'
complete -c ffplay-all -o acodec -d 'X Item "-acodec codec_name" Force a specific audio decoder'
complete -c ffplay-all -o vcodec -d 'X Item "-vcodec codec_name" Force a specific video decoder'
complete -c ffplay-all -o scodec -d 'X Item "-scodec codec_name" Force a specific subtitle decoder'
complete -c ffplay-all -o autorotate -d 'X Item "-autorotate" Automatically rotate the video according to file metadata'
complete -c ffplay-all -o framedrop -d 'X Item "-framedrop" Drop video frames if video is out of sync'
complete -c ffplay-all -o infbuf -d 'X Item "-infbuf" Do not limit the input buffer size, read as much data as pos…'
complete -c ffplay-all -o filter_threads -d 'X Item "-filter_threads nb_threads" Defines how many threads are used to proc…'
complete -c ffplay-all -s 1
complete -c ffplay-all -o drc_scale
complete -c ffplay-all -o use_buggy_lpc
complete -c ffplay-all -o aribb24-base-path
complete -c ffplay-all -o aribb24-skip-ruby-text
complete -c ffplay-all -o sub_type
complete -c ffplay-all -o caption_encoding
complete -c ffplay-all -o font
complete -c ffplay-all -o ass_single_rect
complete -c ffplay-all -o force_outline_text
complete -c ffplay-all -o outline_width
complete -c ffplay-all -o ignore_background
complete -c ffplay-all -o ignore_ruby
complete -c ffplay-all -o replace_drcs
complete -c ffplay-all -o replace_msz_ascii
complete -c ffplay-all -o replace_msz_japanese
complete -c ffplay-all -o replace_msz_glyph
complete -c ffplay-all -o canvas_size
complete -c ffplay-all -s 2 -d 'Compute clut once if no matching CLUT is in the stream'
complete -c ffplay-all -o tag:v
complete -c ffplay-all -o ignore_loop
complete -c ffplay-all -o max_fps
complete -c ffplay-all -o default_fps
complete -c ffplay-all -o no_resync_search
complete -c ffplay-all -o flv_metadata
complete -c ffplay-all -o flv_ignore_prevtag
complete -c ffplay-all -o flv_full_metadata
complete -c ffplay-all -o list_devices
complete -c ffplay-all -o video_device_index
complete -c ffplay-all -o audio_device_index
complete -c ffplay-all -o pixel_format
complete -c ffplay-all -o framerate
complete -c ffplay-all -o video_size
complete -c ffplay-all -o capture_cursor
complete -c ffplay-all -o capture_mouse_clicks
complete -c ffplay-all -o capture_raw_data
complete -c ffplay-all -o list_formats -d 'of channels can be 2, 8 or 16'
complete -c ffplay-all -o timestamps -o ts -d 'conversion into the real time clock'
complete -c ffplay-all -o root
complete -c ffplay-all -o filter/-vf/-af
complete -c ffplay-all -o filter_complex
complete -c ffplay-all -o vf/-af -d 'avfilter_graph_parse_ptr() function defined in libavfilter/avfilter. h'
complete -c ffplay-all -o filter_script
complete -c ffplay-all -o filter_complex_script -d 'TIMELINE EDITING'
complete -c ffplay-all -o '1.0' -d 'audio signal, or "waveform", should be centered around the zero point'
complete -c ffplay-all -o 12 -o 1/10 -d 'this region should be encoded with a QP around one-tenth of the full range be…'
complete -c ffplay-all -o '1000.0' -d 'brightness 4'
complete -c ffplay-all -o init_hw_device
complete -c ffplay-all -o filter_hw_device
complete -c ffplay-all -o 100 -o '0.743643887037158704752191506114774' -d 'start_y 4'
complete -c ffplay-all -o '0.131825904205311970493132056385139' -d mptestsrc

