# ffprobe-all
# Autogenerated from man page /usr/share/man/man1/ffprobe-all.1.gz
complete -c ffprobe-all -s L -d 'X Item "-L" Show license'
complete -c ffprobe-all -s h -s '?' -o help -l help -d 'X Item "-h, -?, -help, --help [arg]" Show help'
complete -c ffprobe-all -o version -d 'X Item "-version" Show version'
complete -c ffprobe-all -o buildconf -d 'X Item "-buildconf" Show the build configuration, one option per line'
complete -c ffprobe-all -o formats -d 'X Item "-formats" Show available formats (including devices)'
complete -c ffprobe-all -o demuxers -d 'X Item "-demuxers" Show available demuxers'
complete -c ffprobe-all -o muxers -d 'X Item "-muxers" Show available muxers'
complete -c ffprobe-all -o devices -d 'X Item "-devices" Show available devices'
complete -c ffprobe-all -o codecs -d 'X Item "-codecs" Show all codecs known to libavcodec'
complete -c ffprobe-all -o decoders -d 'X Item "-decoders" Show available decoders'
complete -c ffprobe-all -o encoders -d 'X Item "-encoders" Show all available encoders'
complete -c ffprobe-all -o bsfs -d 'X Item "-bsfs" Show available bitstream filters'
complete -c ffprobe-all -o protocols -d 'X Item "-protocols" Show available protocols'
complete -c ffprobe-all -o filters -d 'X Item "-filters" Show available libavfilter filters'
complete -c ffprobe-all -o pix_fmts -d 'X Item "-pix_fmts" Show available pixel formats'
complete -c ffprobe-all -o sample_fmts -d 'X Item "-sample_fmts" Show available sample formats'
complete -c ffprobe-all -o layouts -d 'X Item "-layouts" Show channel names and standard channel layouts'
complete -c ffprobe-all -o dispositions -d 'X Item "-dispositions" Show stream dispositions'
complete -c ffprobe-all -o colors -d 'X Item "-colors" Show recognized color names'
complete -c ffprobe-all -o sources -d 'X Item "-sources device[,opt1=val1[,opt2=val2]'
complete -c ffprobe-all -o sinks -d 'X Item "-sinks device[,opt1=val1[,opt2=val2]'
complete -c ffprobe-all -o loglevel -s v -d 'X Item "-loglevel [flags+]loglevel | -v [flags+]loglevel" Set logging level a…'
complete -c ffprobe-all -s 8 -d 'X Item "quiet, -8" Show nothing at all; be silent'
complete -c ffprobe-all -o report -d 'X Item "-report" Dump full command line and log output to a file named \\f(CW\\…'
complete -c ffprobe-all -o hide_banner -d 'X Item "-hide_banner" Suppress printing banner'
complete -c ffprobe-all -o cpuflags -d 'X Item "-cpuflags flags (global)" Allows setting and clearing cpu flags'
complete -c ffprobe-all -o cpucount -d 'X Item "-cpucount count (global)" . PD Override detection of CPU count'
complete -c ffprobe-all -o max_alloc -d 'X Item "-max_alloc bytes" Set the maximum size limit for allocating a block o…'
complete -c ffprobe-all -s f -d 'X Item "-f format" Force format to use'
complete -c ffprobe-all -o unit -d 'X Item "-unit" Show the unit of the displayed values'
complete -c ffprobe-all -o prefix -d 'X Item "-prefix" Use SI prefixes for the displayed values'
complete -c ffprobe-all -o byte_binary_prefix -d 'X Item "-byte_binary_prefix" Force the use of binary prefixes for byte values'
complete -c ffprobe-all -o sexagesimal -d 'X Item "-sexagesimal" Use sexagesimal format HH:MM:SS'
complete -c ffprobe-all -o pretty -d 'X Item "-pretty" Prettify the format of the displayed values, it corresponds …'
complete -c ffprobe-all -o output_format -o of -o print_format -d 'X Item "-output_format, -of, -print_format writer_name[=writer_options]" Set …'
complete -c ffprobe-all -o sections -d 'X Item "-sections" Print sections structure and section information, and exit'
complete -c ffprobe-all -o select_streams -d 'X Item "-select_streams stream_specifier" Select only the streams specified b…'
complete -c ffprobe-all -o show_data -d 'X Item "-show_data" Show payload data, as a hexadecimal and ASCII dump'
complete -c ffprobe-all -o show_data_hash -d 'X Item "-show_data_hash algorithm" Show a hash of payload data, for packets w…'
complete -c ffprobe-all -o show_error -d 'X Item "-show_error" Show information about the error found when trying to pr…'
complete -c ffprobe-all -o show_format -d 'X Item "-show_format" Show information about the container format of the inpu…'
complete -c ffprobe-all -o show_format_entry -d 'X Item "-show_format_entry name" Like -show_format, but only prints the speci…'
complete -c ffprobe-all -o show_entries -d 'X Item "-show_entries section_entries" Set list of entries to show'
complete -c ffprobe-all -o show_packets -d 'X Item "-show_packets" Show information about each packet contained in the in…'
complete -c ffprobe-all -o show_frames -d 'X Item "-show_frames" Show information about each frame and subtitle containe…'
complete -c ffprobe-all -o show_log -d 'X Item "-show_log loglevel" Show logging information from the decoder about e…'
complete -c ffprobe-all -o show_streams -d 'X Item "-show_streams" Show information about each media stream contained in …'
complete -c ffprobe-all -o show_programs -d 'X Item "-show_programs" Show information about programs and their streams con…'
complete -c ffprobe-all -o show_chapters -d 'X Item "-show_chapters" Show information about chapters stored in the format'
complete -c ffprobe-all -o count_frames -d 'X Item "-count_frames" Count the number of frames per stream and report it in…'
complete -c ffprobe-all -o count_packets -d 'X Item "-count_packets" Count the number of packets per stream and report it …'
complete -c ffprobe-all -o read_intervals -d 'X Item "-read_intervals read_intervals" Read only the specified intervals'
complete -c ffprobe-all -o show_private_data -o private -d 'X Item "-show_private_data, -private" Show private data, that is data dependi…'
complete -c ffprobe-all -o show_program_version -d 'X Item "-show_program_version" Show information related to program version'
complete -c ffprobe-all -o show_library_versions -d 'X Item "-show_library_versions" Show information related to library versions'
complete -c ffprobe-all -o show_versions -d 'X Item "-show_versions" Show information related to program and library versi…'
complete -c ffprobe-all -o show_pixel_formats -d 'X Item "-show_pixel_formats" Show information about all pixel formats support…'
complete -c ffprobe-all -o show_optional_fields -d 'X Item "-show_optional_fields value" Some writers viz'
complete -c ffprobe-all -o bitexact -d 'X Item "-bitexact" Force bitexact output, useful to produce output which is n…'
complete -c ffprobe-all -s i -d 'X Item "-i input_url" Read input_url'
complete -c ffprobe-all -s o
complete -c ffprobe-all -s 1
complete -c ffprobe-all -o drc_scale
complete -c ffprobe-all -o use_buggy_lpc
complete -c ffprobe-all -o aribb24-base-path
complete -c ffprobe-all -o aribb24-skip-ruby-text
complete -c ffprobe-all -o sub_type
complete -c ffprobe-all -o caption_encoding
complete -c ffprobe-all -o font
complete -c ffprobe-all -o ass_single_rect
complete -c ffprobe-all -o force_outline_text
complete -c ffprobe-all -o outline_width
complete -c ffprobe-all -o ignore_background
complete -c ffprobe-all -o ignore_ruby
complete -c ffprobe-all -o replace_drcs
complete -c ffprobe-all -o replace_msz_ascii
complete -c ffprobe-all -o replace_msz_japanese
complete -c ffprobe-all -o replace_msz_glyph
complete -c ffprobe-all -o canvas_size
complete -c ffprobe-all -s 2 -d 'Compute clut once if no matching CLUT is in the stream'
complete -c ffprobe-all -o tag:v
complete -c ffprobe-all -o ignore_loop
complete -c ffprobe-all -o max_fps
complete -c ffprobe-all -o default_fps
complete -c ffprobe-all -o no_resync_search
complete -c ffprobe-all -o flv_metadata
complete -c ffprobe-all -o flv_ignore_prevtag
complete -c ffprobe-all -o flv_full_metadata
complete -c ffprobe-all -o list_devices
complete -c ffprobe-all -o video_device_index
complete -c ffprobe-all -o audio_device_index
complete -c ffprobe-all -o pixel_format
complete -c ffprobe-all -o framerate
complete -c ffprobe-all -o video_size
complete -c ffprobe-all -o capture_cursor
complete -c ffprobe-all -o capture_mouse_clicks
complete -c ffprobe-all -o capture_raw_data
complete -c ffprobe-all -o list_formats -d 'of channels can be 2, 8 or 16'
complete -c ffprobe-all -o timestamps -o ts -d 'conversion into the real time clock'
complete -c ffprobe-all -o root
complete -c ffprobe-all -o filter/-vf/-af
complete -c ffprobe-all -o filter_complex
complete -c ffprobe-all -o vf/-af -d 'avfilter_graph_parse_ptr() function defined in libavfilter/avfilter. h'
complete -c ffprobe-all -o filter_script
complete -c ffprobe-all -o filter_complex_script -d 'TIMELINE EDITING'
complete -c ffprobe-all -o '1.0' -d 'audio signal, or "waveform", should be centered around the zero point'
complete -c ffprobe-all -o 12 -o 1/10 -d 'this region should be encoded with a QP around one-tenth of the full range be…'
complete -c ffprobe-all -o '1000.0' -d 'brightness 4'
complete -c ffprobe-all -o init_hw_device
complete -c ffprobe-all -o filter_hw_device
complete -c ffprobe-all -o 100 -o '0.743643887037158704752191506114774' -d 'start_y 4'
complete -c ffprobe-all -o '0.131825904205311970493132056385139' -d mptestsrc

