# fzf-tmux
# Autogenerated from man page /usr/share/man/man1/fzf-tmux.1.gz
complete -c fzf-tmux -s p
complete -c fzf-tmux -s w
complete -c fzf-tmux -s h
complete -c fzf-tmux -s x
complete -c fzf-tmux -s y
complete -c fzf-tmux -s u -d 'Split above (up)'
complete -c fzf-tmux -s d -d 'Split below (down)'
complete -c fzf-tmux -s l -d 'Split left'
complete -c fzf-tmux -s r -d 'Split right'

