# gi-compile-repository
# Autogenerated from man page /usr/share/man/man1/gi-compile-repository.1.gz
complete -c gi-compile-repository -l help -d 'Show help options'
complete -c gi-compile-repository -l output -s o -d 'Save the resulting output in FILENAME'
complete -c gi-compile-repository -l verbose -d 'Show verbose messages'
complete -c gi-compile-repository -l debug -d 'Show debug messages'
complete -c gi-compile-repository -l includedir -d 'Add DIRECTORY to the search path for GIR XML'
complete -c gi-compile-repository -l shared-library -s l -d 'Specifies the shared library where the symbols in the typelib can be found'
complete -c gi-compile-repository -l version -d 'Show programâs version number and exit'

