# gi-decompile-typelib
# Autogenerated from man page /usr/share/man/man1/gi-decompile-typelib.1.gz
complete -c gi-decompile-typelib -l help -d 'Show help options'
complete -c gi-decompile-typelib -l output -s o -d 'Save the resulting output in FILENAME'
complete -c gi-decompile-typelib -l includedir -d 'Add DIRECTORY to the search path for typelibs'
complete -c gi-decompile-typelib -l all -d 'Show all available information'
complete -c gi-decompile-typelib -l version -d 'Show programâs version number and exit'

