# gi-inspect-typelib
# Autogenerated from man page /usr/share/man/man1/gi-inspect-typelib.1.gz
complete -c gi-inspect-typelib -l print-shlibs -d 'Show the shared libraries that implement the NAMESPACE'
complete -c gi-inspect-typelib -l print-typelibs -d 'Show the other typelibs that the NAMESPACE depends on'
complete -c gi-inspect-typelib -l typelib-version -d 'The version of each NAMESPACE to inspect.  For example, the version of Gio-2'

