# git-stripspace
# Autogenerated from man page /usr/share/man/man1/git-stripspace.1.gz
complete -c git-stripspace -s s -l strip-comments -d 'Skip and remove all lines starting with a comment character (default #)'
complete -c git-stripspace -s c -l comment-lines -d 'Prepend the comment character and a blank space to each line'

