# glib-gettextize
# Autogenerated from man page /usr/share/man/man1/glib-gettextize.1.gz
complete -c glib-gettextize -l no-changelog -d OPTIONS
complete -c glib-gettextize -l help -d 'Print help and exit'
complete -c glib-gettextize -l version -d 'Print version information and exit'
complete -c glib-gettextize -s c -l copy -d 'Copy files instead of making symlinks'
complete -c glib-gettextize -s f -l force -d 'Force writing of new files even if old ones exist.  SEE ALSO'

