# glslc
# Autogenerated from man page /usr/share/man/man1/glslc.1.gz
complete -c glslc -o fshader-stage -d 'The -fshader-stage= option overrides #pragma shader_stage(), which overrides …'
complete -c glslc -s S -d 'files, e. g. , -fshader-stage=.  Output file naming'
complete -c glslc -l help -s h
complete -c glslc -l show-limits
complete -c glslc -s o
complete -c glslc -o finvert-y
complete -c glslc -o flimit
complete -c glslc -o flimit-file
complete -c glslc -o std
complete -c glslc -l target-env
complete -c glslc -l target-spv
complete -c glslc -s x
complete -c glslc -s c
complete -c glslc -s E
complete -c glslc -s D
complete -c glslc -o Dmacroname -d 'files are preprocessed'
complete -c glslc -s I
complete -c glslc -o Idirectory -d 'for include files'
complete -c glslc -s g
complete -c glslc -o O0 -o Os
complete -c glslc -s O -d oc
complete -c glslc -o mfmt
complete -c glslc -o fhlsl-16bit-types
complete -c glslc -o fhlsl-offsets
complete -c glslc -o fhlsl-functionality1
complete -c glslc -o fentry-point
complete -c glslc -o fauto-map-locations
complete -c glslc -s w
complete -c glslc -o Werror
complete -c glslc -s M -o MM
complete -c glslc -o MD
complete -c glslc -o MF
complete -c glslc -o MT
complete -c glslc -o fauto-bind-uniforms
complete -c glslc -o fhlsl-iomap
complete -c glslc -o fimage-binding-base
complete -c glslc -o fsampler-binding-base
complete -c glslc -o ftexture-binding-base
complete -c glslc -o fubo-binding-base
complete -c glslc -o fcbuffer-binding-base
complete -c glslc -o fssbo-binding-base
complete -c glslc -o fuav-binding-base
complete -c glslc -o fresource-set-binding

