# gobject-query
# Autogenerated from man page /usr/share/man/man1/gobject-query.1.gz
complete -c gobject-query -s r -d 'Specify the root type'
complete -c gobject-query -s n -d 'Donât descend type tree'
complete -c gobject-query -s b -d 'Specify indent string'
complete -c gobject-query -s i -d 'Specify incremental indent string'
complete -c gobject-query -s s -d 'Specify line spacing'
complete -c gobject-query -s h -l help -d 'Print brief help and exit'
complete -c gobject-query -s v -l version -d 'Print version and exit'

