# gp-archive
# Autogenerated from man page /usr/share/man/man1/gp-archive.1.gz
complete -c gp-archive -l version -d 'X Item "--version" Print the version number and exit'
complete -c gp-archive -l help -d 'X Item "--help" Print usage information and exit'
complete -c gp-archive -s a -d 'X Item "-a {off | on | ldobjects | src | usedldobjects | used[src]}" Specify …'
complete -c gp-archive -s d -d 'X Item "-d path" The path is the absolute path to a common archive, which is …'
complete -c gp-archive -s F -d 'X Item "-F" Force writing, or rewriting of . archive files'
complete -c gp-archive -s m -d 'X Item "-m regex" Archive only those source, object, and debug info files who…'
complete -c gp-archive -s n -d 'X Item "-n" Archive the named experiment only, not any of its descendants'
complete -c gp-archive -s q -d 'X Item "-q" Do not write any warnings to stderr'
complete -c gp-archive -s r -d 'X Item "-r path" This option specifies the location of a common archive'
complete -c gp-archive -s s -d 'X Item "-s selection" Specify archiving of source files'

