# gp-display-html
# Autogenerated from man page /usr/share/man/man1/gp-display-html.1.gz
complete -c gp-display-html -l version -d 'X Item "--version" Print the version number and exit'
complete -c gp-display-html -l help -d 'X Item "--help" Print usage information and exit'
complete -c gp-display-html -l verbose -d 'X Item "--verbose" Enable verbose mode to show diagnostic messages about the …'
complete -c gp-display-html -s d -l debug -d 'X Item "-d [db-vol-size], --debug[=db-vol-size]" Control the printing of run …'
complete -c gp-display-html -l highlight-percentage -d 'X Item "--highlight-percentage=value" Set a percentage value in the interval …'
complete -c gp-display-html -s o -l output -d 'X Item "-o dirname, --output=dirname" Use dirname as the directory name to st…'
complete -c gp-display-html -s O -l overwrite -d 'X Item "-O dirname, --overwrite=dirname" Use dirname as the directory name to…'
complete -c gp-display-html -s q -l quiet -d 'X Item "-q, --quiet" Disable the display of all warning, debug, verbose and a…'
complete -c gp-display-html -l nowarnings

