# grab_color_image
# Autogenerated from man page /usr/share/man/man1/grab_color_image.1.gz
complete -c grab_color_image -l guid -d 'specifies camera to use.  default is the first camera found in the system'
complete -c grab_color_image -l help -d 'print help message'

