# gssdp-device-sniffer
# Autogenerated from man page /usr/share/man/man1/gssdp-device-sniffer.1.gz
complete -c gssdp-device-sniffer -s h -d 'Display help'
complete -c gssdp-device-sniffer -s i -d 'Name of the network interface the sniffer will listen on'
complete -c gssdp-device-sniffer -s 6 -d 'Listen on IPv6 for SSDP announcements AUTHORS Jens Georg'

