# gst-device-monitor-1.0
# Autogenerated from man page /usr/share/man/man1/gst-device-monitor-1.0.1.gz
complete -c 'gst-device-monitor-1.0' -l help -d 'Print help synopsis and available command line options'
complete -c 'gst-device-monitor-1.0' -l version -d 'Print version and exit'
complete -c 'gst-device-monitor-1.0' -s f -l follow -d 'Don\'t exit after showing the initial device list, but wait for devices to be …'

