# gst-discoverer-1.0
# Autogenerated from man page /usr/share/man/man1/gst-discoverer-1.0.1.gz
complete -c 'gst-discoverer-1.0' -l help -d 'Print help synopsis and available FLAGS'
complete -c 'gst-discoverer-1.0' -s v -l verbose -d 'Output all available information'
complete -c 'gst-discoverer-1.0' -s a -l async -d 'Use asynchronous code path'
complete -c 'gst-discoverer-1.0' -s t -l timeout -d 'Specify timeout in seconds (default: 10 seconds)'
complete -c 'gst-discoverer-1.0' -s c -l toc -d 'Output TOC (chapters and editions) if available'

