# gst-inspect-1.0
# Autogenerated from man page /usr/share/man/man1/gst-inspect-1.0.1.gz
complete -c 'gst-inspect-1.0' -l help -d 'Print help synopsis and available FLAGS'
complete -c 'gst-inspect-1.0' -l gst-info-mask -d 'GStreamer info flags to set (list with --help)'
complete -c 'gst-inspect-1.0' -s a -l print-all -d 'Print all plugins and elements'
complete -c 'gst-inspect-1.0' -s b -l print-blacklist -d 'Print list of blacklisted files'
complete -c 'gst-inspect-1.0' -l plugin -d 'List the plugin contents'
complete -c 'gst-inspect-1.0' -l types -d 'Allow inspecting only elements that match all the element types filtered in t…'
complete -c 'gst-inspect-1.0' -l exists -d 'Check if the specified element or plugin exists'
complete -c 'gst-inspect-1.0' -l atleast-version -d 'When checking if an element or plugin exists, also check that its version is …'
complete -c 'gst-inspect-1.0' -s u -l uri-handlers -d 'Print supported URI schemes, with the elements that implement them'
complete -c 'gst-inspect-1.0' -l no-colors -d 'Disable colors in output'
complete -c 'gst-inspect-1.0' -s C -l color -d 'Color output, even when not connected to a tty'
complete -c 'gst-inspect-1.0' -l print-plugin-auto-install-info -d 'Print a machine-parsable list of features the specified plugin provides'
complete -c 'gst-inspect-1.0' -l gst-debug-mask -d 'GStreamer debugging flags to set (list with --help)'
complete -c 'gst-inspect-1.0' -l gst-mask -d 'GStreamer info and debugging flags to set (list with --help)'

