# gst-typefind-1.0
# Autogenerated from man page /usr/share/man/man1/gst-typefind-1.0.1.gz
complete -c 'gst-typefind-1.0' -l help -d 'Print help synopsis and available FLAGS'
complete -c 'gst-typefind-1.0' -l gst-info-mask -d 'GStreamer info flags to set (list with --help)'
complete -c 'gst-typefind-1.0' -l gst-debug-mask -d 'GStreamer debugging flags to set (list with --help)'
complete -c 'gst-typefind-1.0' -l gst-mask -d 'GStreamer info and debugging flags to set (list with --help)'

