# gst-stats-1.0
# Autogenerated from man page /usr/share/man/man1/gst-stats-1.0.1.gz
complete -c 'gst-stats-1.0' -s h -l help -d 'Print help synopsis and available FLAGS'
complete -c 'gst-stats-1.0' -l gst-help-all -d 'Show all help options '

