# gst-play-1.0
# Autogenerated from man page /usr/share/man/man1/gst-play-1.0.1.gz
complete -c 'gst-play-1.0' -l help -d 'Print help synopsis and available command line options'
complete -c 'gst-play-1.0' -l version -d 'Print version and exit'
complete -c 'gst-play-1.0' -l audiosink -d 'Use the SOMESINK element as audio sink instead of autoaudiosink'
complete -c 'gst-play-1.0' -l videosink -d 'Use the SOMESINK element as video sink instead of autovideosink'
complete -c 'gst-play-1.0' -l volume -d 'Set initial playback volume to VOLUME, where 0. 0=silent and 1. 0=unchanged'
complete -c 'gst-play-1.0' -l shuffle -d 'Shuffle playlist (play files in random order)'
complete -c 'gst-play-1.0' -l no-interactive -d 'Disable control through keyboard interaction in terminal (see below)'
complete -c 'gst-play-1.0' -l gapless -d 'Enable gapless playback'
complete -c 'gst-play-1.0' -s v -l flags -d 'Control playback behaviour setting playbin \'flags\' property'
complete -c 'gst-play-1.0' -l verbose -d 'Output status information and property notifications'
complete -c 'gst-play-1.0' -s q -l quiet -d 'Do not print any output (apart from errors)'
complete -c 'gst-play-1.0' -l use-playbin3 -d 'Use playbin3 pipeline (default varies depending on \'USE_PLAYBIN\' env variable)'

