# gtester
# Autogenerated from man page /usr/share/man/man1/gtester.1.gz
complete -c gtester -s h -l help -d 'Print help and exit'
complete -c gtester -s v -l verbose -d 'Print version information and exit'
complete -c gtester -l g-fatal-warnings -d 'Make warnings fatal'
complete -c gtester -s k -l keep-going -d 'Continue running after tests failed'
complete -c gtester -s l -d 'List paths of available test cases'
complete -c gtester -s m -d 'Run test cases in MODE, which can be one of:'
complete -c gtester -s p -d 'Only run test cases matching TEST-PATH'
complete -c gtester -s s -d 'Skip test cases matching TEST-PATH'
complete -c gtester -l seed -d 'Run all test cases with random number seed SEED-STRING'
complete -c gtester -s o -d 'Write the test log to LOG-FILE'
complete -c gtester -s q -l quiet -d 'Suppress per-test-binary output'

