# gtk4-rendernode-tool
# Autogenerated from man page /usr/share/man/man1/gtk4-rendernode-tool.1.gz
complete -c gtk4-rendernode-tool -l undecorated
complete -c gtk4-rendernode-tool -l renderer -d 'Use the given renderer'
complete -c gtk4-rendernode-tool -l runs -d 'Number of times to render the node on each renderer'
complete -c gtk4-rendernode-tool -l no-download -d 'Do not attempt to download the result'
complete -c gtk4-rendernode-tool -l output -d 'Save the differences as a png image in FILE'
complete -c gtk4-rendernode-tool -l quiet -d 'Don\'t write results to stdout'

