# gtk4-builder-tool
# Autogenerated from man page /usr/share/man/man1/gtk4-builder-tool.1.gz
complete -c gtk4-builder-tool -l deprecations -d 'Warn about uses of deprecated types in the UI definition file.  Enumeration'
complete -c gtk4-builder-tool -l callbacks -d 'Print the names of callbacks as well.  Preview'
complete -c gtk4-builder-tool -l id -d 'The ID of the object to preview'
complete -c gtk4-builder-tool -l css -d 'Load style information from the given CSS file.  Render'
complete -c gtk4-builder-tool -l node -d 'Write a serialized node file instead of a png image'
complete -c gtk4-builder-tool -l force -d 'Overwrite an existing file.  Screenshot'
complete -c gtk4-builder-tool -l replace -d 'Write the content back to the UI definition file instead of using the standar…'
complete -c gtk4-builder-tool -l 3to4 -d 'Transform a GTK 3 UI definition file to the equivalent GTK 4 definitions'

