# gtk4-broadwayd
# Autogenerated from man page /usr/share/man/man1/gtk4-broadwayd.1.gz
complete -c gtk4-broadwayd -l port -d 'Use the given PORT for the HTTP connection, instead of the default 8080 + (DI…'
complete -c gtk4-broadwayd -l address -d 'Use the given address for the HTTP connection, instead of the default http://…'
complete -c gtk4-broadwayd -l unixsocket -d 'Use the given address as the unix domain socket address'

