# heif-enc
# Autogenerated from man page /usr/share/man/man1/heif-enc.1.gz
complete -c heif-enc -o qQUALITY -l qualityQUALITY -d 'Defines quality level between 0 and 100 for the generated output file'
complete -c heif-enc -s L -l lossless -d 'Generate lossless output (-q has no effect)'
complete -c heif-enc -o tSIZE -l thumbSIZE -d 'Generate thumbnail with maximum size SIZE pixels (default: off)'
complete -c heif-enc -l no-alpha -d 'Do not save alpha channel'
complete -c heif-enc -l no-thumb-alpha -d 'Do not save alpha channel in thumbnail image'
complete -c heif-enc -o oFILENAME -l outputFILENAME -d 'Output filename (optional)'
complete -c heif-enc -l verbose -d 'Enable logging output (more will increase logging level)'
complete -c heif-enc -s P -l params -d 'Show all encoder parameters'
complete -c heif-enc -o bDEPTH -d 'Bit-depth of generated HEIF file when using 16-bit PNG input (default: 10 bit)'
complete -c heif-enc -s q -l quality -d 'Defines quality level between 0 and 100 for the generated output file'
complete -c heif-enc -s t -l thumb -d 'Generate thumbnail with maximum size SIZE pixels (default: off)'
complete -c heif-enc -s o -l output -d 'Output filename (optional)'
complete -c heif-enc -s b -d 'Bit-depth of generated HEIF file when using 16-bit PNG input (default: 10 bit)'
complete -c heif-enc -s p -d 'Set additional encoder parameters.  See NOTES below.  EXIT STATUS'

