# heif-info
# Autogenerated from man page /usr/share/man/man1/heif-info.1.gz
complete -c heif-info -s d -l dump-boxes -d 'Show a low-level dump of all MP4 file boxes'
complete -c heif-info -o help -l help -d 'Show help.  EXIT STATUS'

