# hwloc-distrib
# Autogenerated from man page /usr/share/man/man1/hwloc-distrib.1.gz
complete -c hwloc-distrib -l single -d 'Singlify each output to a single CPU'
complete -c hwloc-distrib -l taskset -d 'Show CPU set strings in the format recognized by the taskset command-line pro…'
complete -c hwloc-distrib -s v -l verbose -d 'Verbose messages'
complete -c hwloc-distrib -s i -l input -d 'Read the topology from <path> instead of discovering the topology of the loca…'
complete -c hwloc-distrib -l if -l input-format -d 'Enforce the input in the given format, among xml, fsroot, cpuid and synthetic'
complete -c hwloc-distrib -l ignore -d 'Ignore all objects of type <type> in the topology'
complete -c hwloc-distrib -l from -d 'Distribute starting from objects of the given type instead of from the top of…'
complete -c hwloc-distrib -l to -d 'Distribute down to objects of the given type instead of down to the bottom of…'
complete -c hwloc-distrib -l at -d 'Distribute among objects of the given type'
complete -c hwloc-distrib -l reverse -d 'Distribute by starting with the last objects first, and singlify CPU sets by …'
complete -c hwloc-distrib -l restrict -d 'Restrict the topology to the given cpuset'
complete -c hwloc-distrib -l restrict-flags -d 'Enforce flags when restricting the topology'
complete -c hwloc-distrib -l disallowed -d 'Include objects disallowed by administrative limitations'
complete -c hwloc-distrib -l version -d 'Report version and exit'
complete -c hwloc-distrib -s h -l help -d 'Display help message and exit.  DESCRIPTION'

