# hwloc-annotate
# Autogenerated from man page /usr/share/man/man1/hwloc-annotate.1.gz
complete -c hwloc-annotate -l ri -d 'Remove all info attributes that exist with the same name before adding the ne…'
complete -c hwloc-annotate -l ci -d 'Clear the existing info attributes in the target objects before annotating'
complete -c hwloc-annotate -l cu -d 'Clear the existing userdata from the target objects'
complete -c hwloc-annotate -l cd -d 'Clear the existing distances from the topology'
complete -c hwloc-annotate -l version -d 'Report version and exit'
complete -c hwloc-annotate -s h -l help -d 'Display help message and exit.  DESCRIPTION'

