# hwloc-diff
# Autogenerated from man page /usr/share/man/man1/hwloc-diff.1.gz
complete -c hwloc-diff -l refname -d 'Use <name> as the identifier for the reference topology in the output XML dif…'
complete -c hwloc-diff -l version -d 'Report version and exit'
complete -c hwloc-diff -s h -l help -d 'Display help message and exit.  DESCRIPTION'

