# hwloc-dump-hwdata
# Autogenerated from man page /usr/share/man/man1/hwloc-dump-hwdata.1.gz
complete -c hwloc-dump-hwdata -s o -d 'save output files to directory <dir> instead of the default /usr/var/run/hwlo…'
complete -c hwloc-dump-hwdata -l version -d 'Report version and exit'
complete -c hwloc-dump-hwdata -s h -l help -d 'Display help message and exit.  DESCRIPTION'

