# hwloc-compress-dir
# Autogenerated from man page /usr/share/man/man1/hwloc-compress-dir.1.gz
complete -c hwloc-compress-dir -s R -l reverse -d 'Uncompress a previously compressed directory'
complete -c hwloc-compress-dir -s v -l verbose -d 'Display verbose messages'
complete -c hwloc-compress-dir -l version -d 'Report version and exit'
complete -c hwloc-compress-dir -s h -l help -d 'Display help message and exit.  DESCRIPTION'

