# hwloc-gather-cpuid
# Autogenerated from man page /usr/share/man/man1/hwloc-gather-cpuid.1.gz
complete -c hwloc-gather-cpuid -s c -d 'Only gather cpuid values for logical processor whose OS/physical index is <id…'
complete -c hwloc-gather-cpuid -s q -l quiet -s s -l silent -d 'Do not show verbose messages'
complete -c hwloc-gather-cpuid -l version -d 'Report version and exit'
complete -c hwloc-gather-cpuid -s h -l help -d 'Display help message and exit.  DESCRIPTION'

