# hwloc-gather-topology
# Autogenerated from man page /usr/share/man/man1/hwloc-gather-topology.1.gz
complete -c hwloc-gather-topology -l io -d 'Also gather I/O related files'
complete -c hwloc-gather-topology -l dmi -d 'Also gather DMI/SMBIOS related files'
complete -c hwloc-gather-topology -l dt -d 'Also gather Device-Tree CPU files'
complete -c hwloc-gather-topology -l no-cpuid -d 'Do not gather x86 CPUID dump using hwloc-gather-cpuid'
complete -c hwloc-gather-topology -l keep -d 'Keep the temporary copy of dumped files instead of destroying it'
complete -c hwloc-gather-topology -l version -d 'Report version and exit'
complete -c hwloc-gather-topology -s h -l help -d 'Display help message and exit.  DESCRIPTION'

