# hwsim
# Autogenerated from man page /usr/share/man/man1/hwsim.1.gz
complete -c hwsim -l version -s v -d 'Show version number and exit'
complete -c hwsim -l help -s h -d 'Show help message and exit'

