# idn
# Autogenerated from man page /usr/share/man/man1/idn.1.gz
complete -c idn -s h -l help -d 'Print help and exit'
complete -c idn -s V -l version -d 'Print version and exit'
complete -c idn -s s -l stringprep -d 'Prepare string according to nameprep profile'
complete -c idn -s d -l punycode-decode -d 'Decode Punycode'
complete -c idn -s e -l punycode-encode -d 'Encode Punycode'
complete -c idn -s a -l idna-to-ascii -d 'Convert to ACE according to IDNA (default mode)'
complete -c idn -s u -l idna-to-unicode -d 'Convert from ACE according to IDNA'
complete -c idn -l allow-unassigned -d 'Toggle IDNA AllowUnassigned flag (default off)'
complete -c idn -l usestd3asciirules -d 'Toggle IDNA UseSTD3ASCIIRules flag (default off)'
complete -c idn -l no-tld -d 'Don\'t check string for TLD specific rules Only for --idna-to-ascii and --idna…'
complete -c idn -s n -l nfkc -d 'Normalize string according to Unicode v3. 2 NFKC'
complete -c idn -s p -l profile -d 'Use specified stringprep profile instead Valid stringprep profiles: Nameprep …'
complete -c idn -l debug -d 'Print debugging information'
complete -c idn -l quiet -d 'Silent operation AUTHOR Written by Simon Josefsson'

