# ifrename
# Autogenerated from man page /usr/share/man/man8/ifrename.8.gz
complete -c ifrename -s c -d 'Set the configuration file to be used (by default  /etc/iftab )'
complete -c ifrename -s p -d 'Probe (load) kernel modules before renaming interfaces'
complete -c ifrename -s d -d 'Enable various Debian specific hacks.  Combined with'
complete -c ifrename -s i -d 'Only rename the specified interface  as opposed to all interfaces on the syst…'
complete -c ifrename -s n -d 'When used with'
complete -c ifrename -s t -d 'Enable name takeover support'
complete -c ifrename -s u -d 'Enable udev output mode'
complete -c ifrename -s D -d 'Dry-run mode'
complete -c ifrename -s V -d 'Verbose mode'
complete -c ifrename -s C -d 'Count matching interfaces'

