# iptables-save
# Autogenerated from man page /usr/share/man/man8/iptables-save.8.gz
complete -c iptables-save -s M -l modprobe -d 'Specify the path to the modprobe(8) program'
complete -c iptables-save -s f -l file -d 'Specify a filename to log the output to'
complete -c iptables-save -s c -l counters -d 'Include the current values of all packet and byte counters in the output'
complete -c iptables-save -s t -l table -d 'Restrict output to only one table'

