# iso-read
# Autogenerated from man page /usr/share/man/man1/iso-read.1.gz
complete -c iso-read -s d -l debug -d 'Set debugging to LEVEL'
complete -c iso-read -s i -l image -d 'Read from ISO-9660 image.  This option is mandatory'
complete -c iso-read -s e -l extract -d 'Extract FILE from ISO-9660 image.  This option is mandatory'
complete -c iso-read -s k -l ignore -d 'Ignore read error(s), i. e.  keep going'
complete -c iso-read -l no-header -d 'Don\'t display header and copyright (for regression testing)'
complete -c iso-read -s o -l output-file -d 'Output file.  This option is mandatory'
complete -c iso-read -s U -l udf -d 'Contents are in UDF format'
complete -c iso-read -s V -l version -d 'display version and copyright information and exit . SS "Help options:"'
complete -c iso-read -s '?' -l help -d 'Show this help message'
complete -c iso-read -l usage -d 'Display brief usage message AUTHOR Rocky Bernstein <rocky@gnu'

