# iso-info
# Autogenerated from man page /usr/share/man/man1/iso-info.1.gz
complete -c iso-info -s d -l debug -d 'Set debugging to LEVEL'
complete -c iso-info -s i -l input -d 'Filename to read ISO-9960 image from'
complete -c iso-info -s f -d 'Generate output similar to \'find .  -print\''
complete -c iso-info -s l -l iso9660 -d 'output similar to \'ls -lR\' for an ISO 9660 fs'
complete -c iso-info -s U -l udf -d 'output similar to \'ls -lR\' for a UDF fs'
complete -c iso-info -l no-header -d 'Don\'t display header and copyright (for regression'
complete -c iso-info -l no-joliet -d 'Don\'t use Joliet-extension information'
complete -c iso-info -l no-rock-ridge -d 'Don\'t use Rock-Ridge-extension information'
complete -c iso-info -l no-xa -d 'Don\'t use XA-extension information'
complete -c iso-info -s r -l show-rock-ridge -d 'A maximum of UINT files will be considered.  Use 0 for all files'
complete -c iso-info -s q -l quiet -d 'Don\'t produce warning output'
complete -c iso-info -s V -l version -d 'display version and copyright information and exit . SS "Help options:"'
complete -c iso-info -s '?' -l help -d 'Show this help message'
complete -c iso-info -l usage -d 'Display brief usage message AUTHOR Rocky Bernstein <rocky@gnu'

