# iwctl
# Autogenerated from man page /usr/share/man/man1/iwctl.1.gz
complete -c iwctl -l username -s u -d 'Provide username'
complete -c iwctl -l password -s p -d 'Provide password'
complete -c iwctl -l passphrase -s P -d 'Provide passphrase'
complete -c iwctl -l dont-ask -s v -d 'Don\'t ask for missing credentials'
complete -c iwctl -l help -s h -d 'Show help message and exit'

