# jbgtopbm
# Autogenerated from man page /usr/share/man/man1/jbgtopbm.1.gz
complete -c jbgtopbm -s x -d 'Decode only up to the largest resolution layer which is still not more than  …'
complete -c jbgtopbm -s y -d 'Decode only up to the largest resolution layer which is still not more than  …'
complete -c jbgtopbm -s m -d 'Process multiple concatenated BIEs'
complete -c jbgtopbm -s b -d 'Use binary values instead of Gray code words in order to decode pixel values …'
complete -c jbgtopbm -s d -d 'Diagnose a single BIE'
complete -c jbgtopbm -s p -d 'If the input contains multiple bitplanes, then extract only the specified sin…'

