# kernel-install
# Autogenerated from man page /usr/share/man/man8/kernel-install.8.gz
complete -c kernel-install -l esp-path -d 'Path to the EFI System Partition (ESP)'
complete -c kernel-install -l boot-path -d 'Path to the Extended Boot Loader partition, as defined in the \\m[blue]Boot Lo…'
complete -c kernel-install -l make-entry-directory -d 'Controls creation and deletion of the \\m[blue]Boot Loader Specification\\m[]\\s…'
complete -c kernel-install -l entry-token -d 'Controls how to name and identify boot loader entries for this kernel install…'
complete -c kernel-install -s v -l verbose -d 'Output additional information about operations being performed'
complete -c kernel-install -l root -d 'Takes a directory path as an argument'
complete -c kernel-install -l image -d 'Takes a path to a disk image file or block device node'
complete -c kernel-install -s h -l help -d 'Print a short help text and exit'
complete -c kernel-install -l version -d 'Print a short version string and exit'
complete -c kernel-install -l no-pager -d 'Do not pipe output into a pager'
complete -c kernel-install -l json -d 'Shows output formatted as JSON'
complete -c kernel-install -l image-policy -d 'Takes an image policy string as argument, as per systemd. image-policy(7)'
complete -c kernel-install -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'

