# lastlog2
# Autogenerated from man page /usr/share/man/man8/lastlog2.8.gz
complete -c lastlog2 -s b -l before
complete -c lastlog2 -s C -l clear
complete -c lastlog2 -s u -l 'user*'
complete -c lastlog2 -s d
complete -c lastlog2 -s h -l help
complete -c lastlog2 -s i -l import
complete -c lastlog2 -s r -l rename
complete -c lastlog2 -s s -l servive
complete -c lastlog2 -s S -l set
complete -c lastlog2 -s t -l time
complete -c lastlog2 -l users
complete -c lastlog2 -s v -l version

