# luajit
# Autogenerated from man page /usr/share/man/man1/luajit.1.gz
complete -c luajit -s e -d 'Run the given chunk of Lua code'
complete -c luajit -s l -d 'Load the named library, just like require("library")'
complete -c luajit -s b -d 'Save or list bytecode.  Run without arguments to get help on options'
complete -c luajit -s j -d 'Perform LuaJIT control command (optional space after -j)'
complete -c luajit -s O -d 'Control LuaJIT optimizations'
complete -c luajit -s i -d 'Run in interactive mode'
complete -c luajit -s v -d 'Show LuaJIT version'
complete -c luajit -s E -d 'Ignore environment variables'

