# lv2info
# Autogenerated from man page /usr/share/man/man1/lv2info.1.gz
complete -c lv2info -s V -d 'Display version information and exit'
complete -c lv2info -s h -d 'Print the command line options'
complete -c lv2info -s m -d 'Add record of plugin to Turtle manifest file'
complete -c lv2info -s p -d 'Write description of plugin to Turtle file'

