# lxterminal
# Autogenerated from man page /usr/share/man/man1/lxterminal.1.gz
complete -c lxterminal -s e -l command -l command -d 'This option specifies the program (and its command line arguments) to be run …'
complete -c lxterminal -l geometry -d 'Set the terminal\\*(Aqs size in characters and lines'
complete -c lxterminal -s l -l loginshell -d 'Executes login shell'
complete -c lxterminal -s t -l title -l tabs -d 'Set the terminal\\*(Aqs title.  Use comma for multiple tabs'
complete -c lxterminal -l working-directory -d 'Set the terminal\\*(Aqs working directory'

