# lzegrep
# Autogenerated from man page /usr/share/man/man1/lzegrep.1.gz
complete -c lzegrep -s r
complete -c lzegrep -l recursive -d ' 4'
complete -c lzegrep -s R
complete -c lzegrep -l dereference-recursive -d ' 4'
complete -c lzegrep -s d
complete -c lzegrep -l directories -d ' 4'
complete -c lzegrep -s Z
complete -c lzegrep -l null -d ' 4'
complete -c lzegrep -s z
complete -c lzegrep -l null-data -d ' 4'
complete -c lzegrep -l include -d ' 4'
complete -c lzegrep -l exclude -d ' 4'
complete -c lzegrep -l exclude-from -d ' 4'
complete -c lzegrep -l exclude-dir

