# lzfgrep
# Autogenerated from man page /usr/share/man/man1/lzfgrep.1.gz
complete -c lzfgrep -s r
complete -c lzfgrep -l recursive -d ' 4'
complete -c lzfgrep -s R
complete -c lzfgrep -l dereference-recursive -d ' 4'
complete -c lzfgrep -s d
complete -c lzfgrep -l directories -d ' 4'
complete -c lzfgrep -s Z
complete -c lzfgrep -l null -d ' 4'
complete -c lzfgrep -s z
complete -c lzfgrep -l null-data -d ' 4'
complete -c lzfgrep -l include -d ' 4'
complete -c lzfgrep -l exclude -d ' 4'
complete -c lzfgrep -l exclude-from -d ' 4'
complete -c lzfgrep -l exclude-dir

