# lzgrep
# Autogenerated from man page /usr/share/man/man1/lzgrep.1.gz
complete -c lzgrep -s r
complete -c lzgrep -l recursive -d ' 4'
complete -c lzgrep -s R
complete -c lzgrep -l dereference-recursive -d ' 4'
complete -c lzgrep -s d
complete -c lzgrep -l directories -d ' 4'
complete -c lzgrep -s Z
complete -c lzgrep -l null -d ' 4'
complete -c lzgrep -s z
complete -c lzgrep -l null-data -d ' 4'
complete -c lzgrep -l include -d ' 4'
complete -c lzgrep -l exclude -d ' 4'
complete -c lzgrep -l exclude-from -d ' 4'
complete -c lzgrep -l exclude-dir

