# mdmon
# Autogenerated from man page /usr/share/man/man8/mdmon.8.gz
complete -c mdmon -l foreground -d 'Normally,  mdmon will fork and continue in the background'
complete -c mdmon -l takeover -d 'This instructs  mdmon to replace any active  mdmon which is currently monitor…'
complete -c mdmon -l all -d 'This tells mdmon to find any active containers and start monitoring each of t…'
complete -c mdmon -l all-active-arrays -d 'Note that mdmon is automatically started by mdadm when needed and so does not…'

