# mkswap
# Autogenerated from man page /usr/share/man/man8/mkswap.8.gz
complete -c mkswap -s c -l check
complete -c mkswap -s F -l file
complete -c mkswap -s f -l force
complete -c mkswap -s q -l quiet
complete -c mkswap -s L -l label
complete -c mkswap -l lock
complete -c mkswap -s p -l pagesize
complete -c mkswap -s U -l uuid
complete -c mkswap -s e -l endianness
complete -c mkswap -s o -l offset
complete -c mkswap -s s -l size
complete -c mkswap -s v -l swapversion
complete -c mkswap -l verbose
complete -c mkswap -s h -l help
complete -c mkswap -s V -l version

