# nomacs
# Autogenerated from man page /usr/share/man/man1/nomacs.1.gz
complete -c nomacs -l batch
complete -c nomacs -l batch-log
complete -c nomacs -s d -l directory
complete -c nomacs -s f -l fullscreen
complete -c nomacs -s h -l help
complete -c nomacs -l help-all
complete -c nomacs -l import-settings
complete -c nomacs -s m -l mode
complete -c nomacs -s p -l private
complete -c nomacs -l pong
complete -c nomacs -l register-files
complete -c nomacs -l slideshow
complete -c nomacs -s t -l tab
complete -c nomacs -s v -l version

