# nvidia-cuda-mps-control
# Autogenerated from man page /usr/share/man/man1/nvidia-cuda-mps-control.1.gz
complete -c nvidia-cuda-mps-control -o uid -d 'Start a new MPS server for the specified user (UID)'
complete -c nvidia-cuda-mps-control -s t -d 'Shutdown the MPS control daemon process and all MPS servers'
complete -c nvidia-cuda-mps-control -s d -d 'Start the MPS control daemon in background mode, assuming the user has enough…'
complete -c nvidia-cuda-mps-control -s f -d 'Start the MPS control daemon in foreground mode, assuming the user has enough…'
complete -c nvidia-cuda-mps-control -s h -l help -d 'Print a help message'

