# nvidia-persistenced
# Autogenerated from man page /usr/share/man/man1/nvidia-persistenced.1.gz
complete -c nvidia-persistenced -s v -l version -d 'Print the utility version and exit'
complete -c nvidia-persistenced -s h -l help -d 'Print usage information for the command line options and exit'
complete -c nvidia-persistenced -s V -l verbose -d 'Controls how much information is printed'
complete -c nvidia-persistenced -s u -l user -d 'Runs nvidia-persistenced with the user permissions of the user specified by t…'
complete -c nvidia-persistenced -s g -l group -d 'Runs nvidia-persistenced with the group permissions of the group specified by…'
complete -c nvidia-persistenced -l persistence-mode -l no-persistence-mode -d 'By default, nvidia-persistenced starts with persistence mode enabled for all …'
complete -c nvidia-persistenced -l uvm-persistence-mode -l no-uvm-persistence-mode -d 'UVM persistence mode is only supported on the single GPU confidential computi…'
complete -c nvidia-persistenced -l nvidia-cfg-path -d 'The nvidia-cfg library is used to communicate with the NVIDIA kernel module t…'

