# nvidia-modprobe
# Autogenerated from man page /usr/share/man/man1/nvidia-modprobe.1.gz
complete -c nvidia-modprobe -s v -l version -d 'Print the utility version and exit'
complete -c nvidia-modprobe -s h -l help -d 'Print usage information for the command line options and exit'
complete -c nvidia-modprobe -l module-instance -d 'option is specified on systems with multiple NVIDIA kernel modules, nvidia-mo…'
complete -c nvidia-modprobe -l create-nvidia-device-file -d 'option is specified, nvidia-modprobe will also create the requested device fi…'
complete -c nvidia-modprobe -s c -d 'Create the NVIDIA device file with the given minor number; this option can be…'
complete -c nvidia-modprobe -s u -l unified-memory -d 'Load the NVIDIA Unified Memory kernel module or create device files for it, i…'
complete -c nvidia-modprobe -s m -l modeset -d 'Load the NVIDIA modeset kernel module and create its device file'
complete -c nvidia-modprobe -s s -l nvswitch -d 'Load the NVIDIA kernel module and create the NVSwitch device files for each m…'
complete -c nvidia-modprobe -s l -l nvlink -d 'Load the NVIDIA kernel module and create the NVLink control device file'
complete -c nvidia-modprobe -s f -l nvidia-capability-device-file -d 'Create the NVIDIA capability device files with the given capability /proc fil…'
complete -c nvidia-modprobe -s i -l nvidia-imex-channel-device-file -d 'Create the NVIDIA IMEX channel device files for the given minor number range …'
complete -c nvidia-modprobe -s a -l auto-online-movable -d 'Enable the online_movable auto onlining kernel setting for platforms (like Gr…'

