# optipng
# Autogenerated from man page /usr/share/man/man1/optipng.1.gz
complete -c optipng -s '?' -s h -o help -d 'Show a complete summary of options'
complete -c optipng -o backup -o keep -d 'Keep a backup of the modified files'
complete -c optipng -o clobber -d 'Overwrite the existing output and backup files'
complete -c optipng -o dir -d 'Write the output files to directory'
complete -c optipng -o fix -d 'Enable error recovery.  This option has no effect on valid input files'
complete -c optipng -o force -d 'Enforce writing of a new output file'
complete -c optipng -o log -d 'Log messages to file.  For safety reasons, file must have the extension \\fC'
complete -c optipng -o out -d 'Write output file to file'
complete -c optipng -o preserve -d 'Preserve file attributes (time stamps, file access rights, etc'
complete -c optipng -o quiet -o silent -d 'Run in quiet mode'
complete -c optipng -o simulate -d 'Run in simulation mode: perform the trials, but do not create output files'
complete -c optipng -s v -d 'Enable the options -verbose and -version'
complete -c optipng -o verbose -d 'Run in verbose mode'
complete -c optipng -o version -d 'Show copyright, version and build info'
complete -c optipng -s o -d 'Select the optimization level'
complete -c optipng -s f -d 'Select the PNG delta filters'
complete -c optipng -o full -d 'Produce a full report on IDAT.  This option might slow down the trials'
complete -c optipng -s i -d 'Select the interlace type (0-1)'
complete -c optipng -o nb -d 'Do not apply bit depth reduction'
complete -c optipng -o nc -d 'Do not apply color type reduction'
complete -c optipng -o np -d 'Do not apply palette reduction'
complete -c optipng -o nx -d 'Do not apply any lossless image reduction: enable the options -nb, -nc and -np'
complete -c optipng -o nz -d 'Do not recode IDAT datastreams'
complete -c optipng -o zc -d 'Select the zlib compression levels used in IDAT compression'
complete -c optipng -o zm -d 'Select the zlib memory levels used in IDAT compression'
complete -c optipng -o zs -d 'Select the zlib compression strategies used in IDAT compression'
complete -c optipng -o zw -d 'Select the zlib window size (32k,16k,8k,4k,2k,1k,512,256) used in IDAT compre…'
complete -c optipng -o snip -d 'Cut one image out of multi-image, animation or video files'
complete -c optipng -o strip -d 'Strip metadata objects from a PNG file'
complete -c optipng -o o3
complete -c optipng -o f0
complete -c optipng -o f3-5
complete -c optipng -o zs0 -o zs1 -o zs2-3 -o zs0 -o zs0-3

