# p11-kit
# Autogenerated from man page /usr/share/man/man8/p11-kit.8.gz
complete -c p11-kit -s v -l verbose
complete -c p11-kit -s q -l quiet
complete -c p11-kit -l only-uris -d 'is given, only the matching token URIs are printed.  LIST OBJECTS'
complete -c p11-kit -l file
complete -c p11-kit -l label
complete -c p11-kit -l type
complete -c p11-kit -l bits
complete -c p11-kit -l curve
complete -c p11-kit -l profile

