# pam_systemd_loadkey
# Autogenerated from man page /usr/share/man/man8/pam_systemd_loadkey.8.gz
complete -c pam_systemd_loadkey -l keyname -d 'pam_systemd_loadkey via the keyname= option.  OPTIONS'
complete -c pam_systemd_loadkey -o auth
complete -c pam_systemd_loadkey -o session

