# pcilmr
# Autogenerated from man page /usr/share/man/man8/pcilmr.8.gz
complete -c pcilmr -l margin -d 'Margin selected Links'
complete -c pcilmr -l full -d 'Margin all ready for testing (in a meaning similar to the  --scan option) Lin…'
complete -c pcilmr -l scan -d 'Scan for Links with negotiated speed 16 GT/s or higher'
complete -c pcilmr -s c -d 'Print Device Lane Margining Capabilities only.  Do not run margining'
complete -c pcilmr -s l -d 'Specify lanes for margining'
complete -c pcilmr -s e -d 'Specify Error Count Limit for margining. br Default: 4'
complete -c pcilmr -s r -d 'Specify Receivers to select margining targets'
complete -c pcilmr -s p -d 'Specify number of lanes to margin simultaneously'
complete -c pcilmr -s T -d 'Time Margining will continue until the Error Count is no more than an Error C…'
complete -c pcilmr -s t -d 'Specify maximum number of steps for Time Margining'
complete -c pcilmr -s V -d 'Same as  -T option, but for Voltage'
complete -c pcilmr -s v -d 'Specify maximum number of steps for Voltage Margining'
complete -c pcilmr -s o -d 'Save margining results in csv form into the specified directory'

