# pcsc-spy
# Autogenerated from man page /usr/share/man/man1/pcsc-spy.1.gz
complete -c pcsc-spy -s d -l diffable -d 'X Item "-d, --diffable" Remove the variable parts (like handler values) from …'
complete -c pcsc-spy -s h -l help -d 'X Item "-h, --help" Display a short help text'
complete -c pcsc-spy -s n -l nocolor -d 'X Item "-n, --nocolor" Disable the output colorization (if you want redirect …'
complete -c pcsc-spy -s v -l version -d 'X Item "-v, --version" Print the version of the pcsc-spy program plus a copyr…'
complete -c pcsc-spy -s t -l thread

