# picom-trans
# Autogenerated from man page /usr/share/man/man1/picom-trans.1.gz
complete -c picom-trans -s w -l window -d 'Specify the window id of the target window'
complete -c picom-trans -s n -l name -d 'Specify and try to match a window name'
complete -c picom-trans -s c -l current -d 'Specify the currently active window as target'
complete -c picom-trans -s s -l select -d 'Select target window with mouse cursor'
complete -c picom-trans -s o -l opacity -d 'Specify the new opacity value for the window'
complete -c picom-trans -s g -l get -d 'Print the target window\'s opacity instead of setting it'
complete -c picom-trans -s d -l delete -d 'Delete opacity of the target window instead of setting it'
complete -c picom-trans -s t -l toggle -d 'Toggle the target window\'s opacity: Set opacity if not already set, and delet…'
complete -c picom-trans -s r -l reset -d 'Reset opacity for all windows instead of setting it'

