# pipewire-pulse
# Autogenerated from man page /usr/share/man/man1/pipewire-pulse.1.gz
complete -c pipewire-pulse -s h -l help -d 'Show help'
complete -c pipewire-pulse -s v -l verbose -d 'Increase the verbosity by one level'
complete -c pipewire-pulse -l version -d 'Show version information'
complete -c pipewire-pulse -s c -l config -d 'Load the given config file (Default: pipewire-pulse. conf)'

