# poweroff
# Autogenerated from man page /usr/share/man/man8/poweroff.8.gz
complete -c poweroff -l help
complete -c poweroff -l halt
complete -c poweroff -s p -l poweroff
complete -c poweroff -l reboot
complete -c poweroff -s f -l force
complete -c poweroff -s w -l wtmp-only
complete -c poweroff -s d -l no-wtmp
complete -c poweroff -s n -l no-sync
complete -c poweroff -l no-wall

