# pw-cat
# Autogenerated from man page /usr/share/man/man1/pw-cat.1.gz
complete -c pw-cat -s h -l help -d 'Show help'
complete -c pw-cat -l version -d 'Show version information'
complete -c pw-cat -s v -l verbose -d 'Verbose operation'
complete -c pw-cat -s R -l remote -d 'The name the remote instance to connect to'
complete -c pw-cat -s p -l playback -d 'Playback mode.  Read data from the specified file, and play it back'
complete -c pw-cat -s r -l record -d 'Recording mode.  Capture data and write it to the specified file'
complete -c pw-cat -s m -l midi -d 'MIDI mode.  FILE is a MIDI file'
complete -c pw-cat -s d -l dsd -d 'DSD mode.  FILE is a DSF file'
complete -c pw-cat -l media-type -d 'Set the media type property (default Audio/Midi depending on mode)'
complete -c pw-cat -l media-category -d 'Set the media category property (default Playback/Capture depending on mode)'
complete -c pw-cat -l media-role -d 'Set the media role property (default Music)'
complete -c pw-cat -l target
complete -c pw-cat -l latency
complete -c pw-cat -s P -l properties
complete -c pw-cat -s q -l quality
complete -c pw-cat -l rate
complete -c pw-cat -l channels
complete -c pw-cat -l channel-map
complete -c pw-cat -l format
complete -c pw-cat -l volume

