# pw-config
# Autogenerated from man page /usr/share/man/man1/pw-config.1.gz
complete -c pw-config -s h -l help
complete -c pw-config -l version
complete -c pw-config -s n -l name
complete -c pw-config -s p -l prefix
complete -c pw-config -s L -l no-newline
complete -c pw-config -s r -l recurse
complete -c pw-config -s N -l no-colors
complete -c pw-config -s C -o color

