# pw-dump
# Autogenerated from man page /usr/share/man/man1/pw-dump.1.gz
complete -c pw-dump -s h -l help -d 'Show help'
complete -c pw-dump -s r -l remote -d 'The name of the remote instance to dump'
complete -c pw-dump -s m -l monitor -d 'Monitor PipeWire state changes, and output JSON arrays describing changes'
complete -c pw-dump -s N -l no-colors -d 'Disable color output'
complete -c pw-dump -s C -l color -d 'Whether to enable color support.  WHEN is never, always, or auto'

