# pw-jack
# Autogenerated from man page /usr/share/man/man1/pw-jack.1.gz
complete -c pw-jack -s h -d 'Show help'
complete -c pw-jack -s r -d 'The name of the remote instance to connect to'
complete -c pw-jack -s v -d 'Verbose operation'

