# pw-loopback
# Autogenerated from man page /usr/share/man/man1/pw-loopback.1.gz
complete -c pw-loopback -s h -l help -d 'Show help'
complete -c pw-loopback -s r -l remote -d 'The name of the remote instance to connect to'
complete -c pw-loopback -s n -l name -d 'Name of the loopback node'
complete -c pw-loopback -s g -l group -d 'Name of the loopback node group'
complete -c pw-loopback -s c -l channels -d 'Number of channels to provide'
complete -c pw-loopback -s m -l channel-map -d 'Channel map (default [ FL, FR ])'
complete -c pw-loopback -s l -l latency -d 'Desired latency in ms'
complete -c pw-loopback -s d -l delay -d 'Added delay in seconds (floating point allowed)'
complete -c pw-loopback -s C -l capture -d 'Target device to capture from'
complete -c pw-loopback -s P -l playback -d 'Target device to play to'
complete -c pw-loopback -l capture-props -d 'Wanted properties of capture node (in JSON)'
complete -c pw-loopback -l playback-props -d 'Wanted properties of capture node (in JSON)'

