# pw-link
# Autogenerated from man page /usr/share/man/man1/pw-link.1.gz
complete -c pw-link -s r -l remote
complete -c pw-link -s h -l help
complete -c pw-link -l version
complete -c pw-link -s o -l output
complete -c pw-link -s i -l input
complete -c pw-link -s l -l links
complete -c pw-link -s m -l monitor
complete -c pw-link -s I -l id
complete -c pw-link -s v -l verbose
complete -c pw-link -s L -l linger
complete -c pw-link -s P -l passive
complete -c pw-link -s p -l props
complete -c pw-link -s d -l disconnect

