# pw-reserve
# Autogenerated from man page /usr/share/man/man1/pw-reserve.1.gz
complete -c pw-reserve -s r -l release -d 'Request any client currently holding the device to release it, and try to res…'
complete -c pw-reserve -s n -l name
complete -c pw-reserve -s a -l appname
complete -c pw-reserve -s p -l priority
complete -c pw-reserve -s m -l monitor
complete -c pw-reserve -s h -l help
complete -c pw-reserve -l version

