# pw-top
# Autogenerated from man page /usr/share/man/man1/pw-top.1.gz
complete -c pw-top -s h -l help -d 'Show help'
complete -c pw-top -s b -l batch-mode -d 'Run in non-interactive batch mode, similar to top\\\'s batch mode'
complete -c pw-top -s n -l iterations -d 'Exit after NUMBER of batch iterations.  Only used in batch mode'
complete -c pw-top -s r -l remote -d 'The name the remote instance to monitor'
complete -c pw-top -s V -l version -d 'Show version information'

