# pygmentize
# Autogenerated from man page /usr/share/man/man1/pygmentize.1.gz
complete -c pygmentize -s l -d 'Set the lexer name'
complete -c pygmentize -s g -d 'Attempt to guess the lexer from the file contents, or pass through as plain t…'
complete -c pygmentize -s F -d 'Add a filter to the token stream'
complete -c pygmentize -s f -d 'Set the formatter name'
complete -c pygmentize -s o -d 'Set output file.  If not given, stdout is used'
complete -c pygmentize -s O -d 'With this option, you can give the lexer and formatter a comma-separated list…'
complete -c pygmentize -s P -d 'This option adds lexer and formatter options like the -O option, but you can …'
complete -c pygmentize -s S -d 'Print out style definitions for style <style> and for formatter <formatter>'
complete -c pygmentize -s L -d 'List lexers, formatters, styles or filters'
complete -c pygmentize -s N -d 'Guess and print out a lexer name based solely on the given filename'
complete -c pygmentize -s C -d 'Like -N, but guess a lexer based on content read from standard input'
complete -c pygmentize -s H -d 'Print detailed help for the object <name> of type <type>, where <type> is one…'
complete -c pygmentize -s h -d 'Show help screen'
complete -c pygmentize -s a -d 'is formatter dependent and can be found in the documentation'
complete -c pygmentize -s V -d 'Show version of the Pygments package'

