# resize
# Autogenerated from man page /usr/share/man/man1/resize.1.gz
complete -c resize -s c -d 'This option indicates that C shell commands should be generated even if the u…'
complete -c resize -s s -d 'This option indicates that Sun console escape sequences will be used instead …'
complete -c resize -s u -d 'This option indicates that Bourne shell commands should be generated even if …'
complete -c resize -s v -d 'This causes resizeand then exit'

