# rg
# Autogenerated from man page /usr/share/man/man1/rg.1.gz
complete -c rg -s e -l regexp
complete -c rg -o f/--file -d 'This flag can also be used when searching for patterns that start with a dash'
complete -c rg -s f -l file
complete -c rg -l pre
complete -c rg -l no-pre -d 'WARNING When this flag is set, ripgrep will unconditionally spawn a process f…'
complete -c rg -l pre-glob
complete -c rg -s z -l search-zip
complete -c rg -s s -l case-sensitive
complete -c rg -l crlf
complete -c rg -l dfa-size-limit
complete -c rg -s E -l encoding
complete -c rg -l engine
complete -c rg -o e/--regexp
complete -c rg -s F -l fixed-strings
complete -c rg -s i -l ignore-case
complete -c rg -s v -l invert-match
complete -c rg -l files-without-match -d 'matching lines'
complete -c rg -s x -l line-regexp
complete -c rg -s m -l max-count
complete -c rg -l mmap
complete -c rg -s U -l multiline
complete -c rg -l multiline-dotall -d 'default.  This flag only applies when multiline search is enabled'
complete -c rg -o U/--multiline -d enabled
complete -c rg -l no-unicode
complete -c rg -l null-data
complete -c rg -s P -l pcre2
complete -c rg -l regex-size-limit
complete -c rg -s S -l smart-case
complete -c rg -l stop-on-nonmatch
complete -c rg -s a -l text
complete -c rg -s j -l threads
complete -c rg -s w -l word-regexp
complete -c rg -l auto-hybrid-regex
complete -c rg -l no-pcre2-unicode
complete -c rg -l binary
complete -c rg -s L -l follow
complete -c rg -l no-messages
complete -c rg -s g -l glob
complete -c rg -l glob-case-insensitive
complete -c rg -l hidden
complete -c rg -l iglob
complete -c rg -l ignore-file
complete -c rg -l ignore-file-case-insensitive
complete -c rg -s d -l max-depth
complete -c rg -l max-filesize
complete -c rg -l no-ignore
complete -c rg -l no-ignore-exclude -l no-ignore-global -l no-ignore-parent
complete -c rg -l no-ignore-vcs
complete -c rg -o u/--unrestricted
complete -c rg -l no-ignore-dot
complete -c rg -l no-ignore-files
complete -c rg -l no-require-git
complete -c rg -l one-file-system
complete -c rg -s t -l type
complete -c rg -o t/--type
complete -c rg -s T -l type-not
complete -c rg -l type-add
complete -c rg -l type-clear -d 'of ripgrep'
complete -c rg -s u -l unrestricted
complete -c rg -o './--hidden' -d 'Three -u/--unrestricted flags is equivalent to --no-ignore -. /--hidden'
complete -c rg -s A -l after-context
complete -c rg -o C/--context
complete -c rg -s B -l before-context
complete -c rg -l block-buffered
complete -c rg -s b -l byte-offset
complete -c rg -l color
complete -c rg -l vimgrep -l json -d 'The possible values for this flag are:'
complete -c rg -l colors
complete -c rg -l column
complete -c rg -s C -l context
complete -c rg -o B/--before-context -d 'the order.  For example, -A2 -C1 is equivalent to -A2 -B1'
complete -c rg -l context-separator
complete -c rg -l no-context-separator
complete -c rg -l field-context-separator
complete -c rg -l field-match-separator
complete -c rg -l heading
complete -c rg -s h -l help
complete -c rg -l hostname-bin
complete -c rg -l hyperlink-format
complete -c rg -o H/--with-filename
complete -c rg -l include-zero
complete -c rg -l line-buffered
complete -c rg -s n -l line-number
complete -c rg -s N -l no-line-number
complete -c rg -s M -l max-columns
complete -c rg -l max-columns-preview
complete -c rg -s 0 -l null
complete -c rg -s o -l only-matching
complete -c rg -l path-separator
complete -c rg -l passthru
complete -c rg -s p -l pretty
complete -c rg -s q -l quiet
complete -c rg -s r -l replace
complete -c rg -l sort
complete -c rg -l sortr
complete -c rg -l trim
complete -c rg -s H -l with-filename
complete -c rg -s I -l no-filename
complete -c rg -l sort-files
complete -c rg -s c -l count
complete -c rg -l count-matches
complete -c rg -s l -l files-with-matches
complete -c rg -o l/--files-with-matches -o c/--count
complete -c rg -o o/--only-matching -o r/--replace -o M/--max-columns -d 'have no effect when --json is set'
complete -c rg -l debug
complete -c rg -l no-ignore-messages
complete -c rg -l stats
complete -c rg -l trace
complete -c rg -l files
complete -c rg -l generate
complete -c rg -l no-config
complete -c rg -l pcre2-version
complete -c rg -l type-list
complete -c rg -s V -l version
complete -c rg -o L/--follow
complete -c rg -o uu
complete -c rg -o uuu
complete -c rg -o a/--text -d 'line terminators, which typically prevents exorbitant memory usage'

