# sordi
# Autogenerated from man page /usr/share/man/man1/sordi.1.gz
complete -c sordi -s h -d 'Print the command line options'
complete -c sordi -s i -d 'Read input as syntax'
complete -c sordi -s o -d 'Write output as syntax'
complete -c sordi -s s -d 'Parse string input instead of a file (terminates options)'
complete -c sordi -s v -d 'Display version information and exit'

