# sord_validate
# Autogenerated from man page /usr/share/man/man1/sord_validate.1.gz
complete -c sord_validate -s h -d 'Print the command line options'
complete -c sord_validate -s l -d 'Print errors on a single line'
complete -c sord_validate -s v -d 'Display version information and exit'

