# spa-resample
# Autogenerated from man page /usr/share/man/man1/spa-resample.1.gz
complete -c spa-resample -s r -l rate -d 'Output sample rate'
complete -c spa-resample -s f -l format -d 'Output sample format (s8 | s16 | s32 | f32 | f64)'
complete -c spa-resample -s q -l quality -d 'Resampler output quality (0-14)'
complete -c spa-resample -s c -l cpuflags -d 'See spa/support/cpu. h'
complete -c spa-resample -s h -d 'Show help'
complete -c spa-resample -s v -d 'Verbose operation'

