# sudo
# Autogenerated from man page /usr/share/man/man1/sudo.1.gz
complete -c sudo -s i -l login
complete -c sudo -s n -l non-interactive
complete -c sudo -s s -l shell
complete -c sudo -s u -l user
complete -c sudo -s h -l help

