# systemd-path
# Autogenerated from man page /usr/share/man/man1/systemd-path.1.gz
complete -c systemd-path -l suffix -d 'Printed paths are suffixed by the specified string. sp Added in version 215'
complete -c systemd-path -l no-pager -d 'Do not pipe output into a pager. sp Added in version 255'
complete -c systemd-path -s h -l help -d 'Print a short help text and exit'
complete -c systemd-path -l version -d 'Print a short version string and exit'

