# systemd-pcrlock
# Autogenerated from man page /usr/share/man/man8/systemd-pcrlock.8.gz
complete -c systemd-pcrlock -l raw-description -d 'When displaying the TPM2 event log do not attempt to decode the records to pr…'
complete -c systemd-pcrlock -l pcr -d 'Specifies the PCR number to use'
complete -c systemd-pcrlock -l nv-index -d 'Specifies to NV index to store the policy in.  Honoured by make-policy'
complete -c systemd-pcrlock -l components -d 'Takes a path to read *. pcrlock and *. pcrlock. d/*. pcrlock files from'
complete -c systemd-pcrlock -l location -d 'Takes either a string or a colon-separated pair of strings'
complete -c systemd-pcrlock -l recovery-pin -d 'Takes a boolean.  Defaults to false.  Honoured by make-policy'
complete -c systemd-pcrlock -l pcrlock -d 'Takes a file system path as argument'
complete -c systemd-pcrlock -l policy -d 'Takes a file system path as argument'
complete -c systemd-pcrlock -l force -d 'If specified with make-policy, the predicted policy will be written to the NV…'
complete -c systemd-pcrlock -l json -d 'Shows output formatted as JSON'
complete -c systemd-pcrlock -l no-pager -d 'Do not pipe output into a pager'
complete -c systemd-pcrlock -s h -l help -d 'Print a short help text and exit'
complete -c systemd-pcrlock -l version -d 'Print a short version string and exit'
complete -c systemd-pcrlock -l tpm2-pcrlock -d 'switches of these tools'
complete -c systemd-pcrlock -l pcrs -d 'is specified'

