# systemd-hwdb
# Autogenerated from man page /usr/share/man/man8/systemd-hwdb.8.gz
complete -c systemd-hwdb -l usr -d 'Generate in /usr/lib/udev instead of /etc/udev. sp Added in version 219'
complete -c systemd-hwdb -s r -l root -d 'Alternate root path in the filesystem. sp Added in version 219'
complete -c systemd-hwdb -s s -l strict -d 'When updating, return non-zero exit value on any parsing error'
complete -c systemd-hwdb -s h -l help -d 'Print a short help text and exit'

