# ts_calibrate
# Autogenerated from man page /usr/share/man/man1/ts_calibrate.1.gz
complete -c ts_calibrate -s r -l rotate -d 'Rotate the screen'
complete -c ts_calibrate -s t -l min_interval -d 'The time in milliseconds that has to pass before a crosshair is pressed by th…'
complete -c ts_calibrate -s c -l validate -d 'Validate the calibration.  Make sure the linear module is configured in ts'
complete -c ts_calibrate -s b -l boundary -d 'Validation boundary in pixels.  Available only when --validate is used'
complete -c ts_calibrate -s l -l loops -d 'Number of loops in validation mode.  Available only when --validate is used'

