# ts_print_mt
# Autogenerated from man page /usr/share/man/man1/ts_print_mt.1.gz
complete -c ts_print_mt -s i -l idev -d 'Explicitly choose the original input event device for tslib to use'
complete -c ts_print_mt -s r -l raw -d 'Don\'t use the filters.  This uses ts_read_raw_mt() instead of ts_read_mt()'
complete -c ts_print_mt -s n -l non-blocking -d 'Opens the input device in non-blocking mode and indefinitely prints the error…'
complete -c ts_print_mt -s s -l samples -d 'Number of samples tslib should read before returning'
complete -c ts_print_mt -s j -l slots -d 'Override the number of concurrent touch contacts to allocate'
complete -c ts_print_mt -s h -l help

