# ts_test_mt
# Autogenerated from man page /usr/share/man/man1/ts_test_mt.1.gz
complete -c ts_test_mt -s r -l rotate -d 'Rotate the screen'
complete -c ts_test_mt -s v -l verbose -d 'Print the input samples\' values to the console'
complete -c ts_test_mt -s j -l slots -d 'Override the number of concurrent touch contacts to allocate'
complete -c ts_test_mt -s i -l idev -d 'Explicitly choose the original input event device for tslib to use'
complete -c ts_test_mt -s n -l samples -d 'Automatically exit after having read n samples'
complete -c ts_test_mt -s a -l altcross -d 'Show an alternative crosshair symbol at the touch points.  SEE ALSO'

