# ts_uinput
# Autogenerated from man page /usr/share/man/man1/ts_uinput.1.gz
complete -c ts_uinput -s d -l daemonize -d 'Start ts_uinput as a daemon and return'
complete -c ts_uinput -s v -l verbose -d 'Print debug information to stdout and stderr'
complete -c ts_uinput -s n -l name -d 'Set the name of the new input event device.  Default: ts_uinput'
complete -c ts_uinput -s i -l idev -d 'Explicitly choose the original input event device for tslib to use'
complete -c ts_uinput -s f -l fbdev -d 'Explicitly choose the framebuffer device to use'
complete -c ts_uinput -s s -l slots -d 'Explicitly set the possible concurrent touch contacts supported'
complete -c ts_uinput -s b -l nofb -d 'Read the screen resolution values from the input device, not the framebuffer …'

