# uchardet
# Autogenerated from man page /usr/share/man/man1/uchardet.1.gz
complete -c uchardet -s v -d 'Print version and build information'
complete -c uchardet -s h -d 'Print help text.  uchardet Command Line Interface'

