# xarchiver
# Autogenerated from man page /usr/share/man/man1/xarchiver.1.gz
complete -c xarchiver -s a -l add -d 'add to archive by asking which files and quit'
complete -c xarchiver -s c -l compress -d 'add the given files by asking the name of the archive and quit'
complete -c xarchiver -s d -l ensure-directory -d 'extract archive to a containing directory and quit'
complete -c xarchiver -s e -l extract -d 'extract archive by asking the extraction directory and quit'
complete -c xarchiver -s m -l multi-extract -d 'extract multiple archives by asking the extraction directory and quit'
complete -c xarchiver -s x -l extract-to -d 'extract archive to the destination directory and quit'
complete -c xarchiver -s i -l info -d 'show found command-line programs to be used and exit'
complete -c xarchiver -s v -l version -d 'show version and exit'
complete -c xarchiver -l display -d 'X display to use'
complete -c xarchiver -s '?' -s h -l help -d 'show help options'
complete -c xarchiver -l help-gtk -d 'show GTK+ options'
complete -c xarchiver -l help-all -d 'show all help options AUTHOR Ingo Br[:u]ckl, (Giuseppe Torelli until 2014) RE…'

