# xclip-copyfile
# Autogenerated from man page /usr/share/man/man1/xclip-copyfile.1.gz
complete -c xclip-copyfile -s p -d 'preserve path formation xclip-pastefile pastes the files out of the clipboard…'

