# xclip
# Autogenerated from man page /usr/share/man/man1/xclip.1.gz
complete -c xclip -s i -o in -d 'read text into X selection from standard input or files (default)'
complete -c xclip -s o -o out -d 'print the selection to standard out (generally for piping to a file or progra…'
complete -c xclip -s f -o filter -d 'when xclip is invoked in the in mode with output level set to silent (the def…'
complete -c xclip -s r -o rmlastnl -d 'when the last character of the selection is a newline character, remove it'
complete -c xclip -s l -o loops -d 'number of X selection requests (pastes into X applications) to wait for befor…'
complete -c xclip -s t -o target -d 'specify a particular data format using the given target atom'
complete -c xclip -s d -o display -d 'X display to use (e. g'
complete -c xclip -s h -o help -d 'show quick summary of options'
complete -c xclip -o selection -d 'specify which X selection to use, options are "primary" to use XA_PRIMARY (de…'
complete -c xclip -o version -d 'show version information'
complete -c xclip -o silent -d 'fork into the background to wait for requests, no informational output, error…'
complete -c xclip -o quiet -d 'show informational messages on the terminal and run in the foreground'
complete -c xclip -o verbose -d 'provide a running commentary of what xclip is doing'
complete -c xclip -o noutf8 -d 'operate in legacy (i. e'

