# xkbcli-interactive-x11
# Autogenerated from man page /usr/share/man/man1/xkbcli-interactive-x11.1.gz
complete -c xkbcli-interactive-x11 -o '\\-help' -d 'Print help and exit'
complete -c xkbcli-interactive-x11 -o '\\-enable\\-compose' -d 'Enable Compose functionality El SEE ALSO xkbcli 1, xkbcli\\-interactive\\-evdev…'

