# xkbcli-compile-compose
# Autogenerated from man page /usr/share/man/man1/xkbcli-compile-compose.1.gz
complete -c xkbcli-compile-compose -o '\\-help' -d 'Print help and exit'
complete -c xkbcli-compile-compose -o '\\-file' -d 'Specify a Compose file to load'
complete -c xkbcli-compile-compose -o '\\-locale' -d 'Specify the locale directly, instead of relying on the environment variables …'

