# xss-lock
# Autogenerated from man page /usr/share/man/man1/xss-lock.1.gz
complete -c xss-lock -s n -l notifier -d 'Run cmd when the screen saver activates because of user inactivity'
complete -c xss-lock -s l -l tranfer-sleep-lock -d 'Allow the locker process to inherit the file descriptor that represents the d…'
complete -c xss-lock -l ignore-sleep -d 'Do not lock on suspend/hibernate'
complete -c xss-lock -s q -l quiet -d 'Output only fatal errors'
complete -c xss-lock -s v -l verbose -d 'Output more messages'
complete -c xss-lock -s h -l help -d 'Print help message and exit'
complete -c xss-lock -l version -d 'Print version number and exit'

