# xxd
# Autogenerated from man page /usr/share/man/man1/xxd.1.gz
complete -c xxd -s a -o autoskip -d 'Toggle autoskip: A single \'*\' replaces NUL-lines.   Default off'
complete -c xxd -s b -o bits -d 'Switch to bits (binary digits) dump, rather than hex dump'
complete -c xxd -s c -o cols -d 'Format . RI < cols > octets per line.  Default 16 (-i: 12, -ps: 30, -b: 6)'
complete -c xxd -s C -o capitalize -d 'Capitalize variable names in C include file style, when using -i'
complete -c xxd -s E -o EBCDIC -d 'Change the character encoding in the righthand column from ASCII to EBCDIC'
complete -c xxd -s e -d 'Switch to little-endian hex dump'
complete -c xxd -s g -o groupsize -d 'Separate the output of every '
complete -c xxd -s h -o help -d 'Print a summary of available commands and exit.   No hex dumping is performed'
complete -c xxd -s i -o include -d 'Output in C include file style'
complete -c xxd -s l -o len -d 'Stop after writing . RI  < len > octets'
complete -c xxd -s n -o name -d 'Override the variable name output when -i is used'
complete -c xxd -s o -d 'Add . RI < offset > to the displayed file position'
complete -c xxd -s p -o ps -o postscript -o plain -d 'Output in PostScript continuous hex dump style'
complete -c xxd -s r -o revert -d 'Reverse operation: convert (or patch) hex dump into binary'
complete -c xxd -s R -d 'In output the hex-value and the value are both colored with the same color de…'
complete -c xxd -o seek -d 'When used after R -r : revert with '
complete -c xxd -s s -d 'Start at . RI < seek > bytes abs.  (or rel. ) infile offset'
complete -c xxd -s u -d 'Use upper-case hex letters.  Default is lower-case'
complete -c xxd -o c8
complete -c xxd -s v -o version -d 'Show version string.  CAVEATS'
complete -c xxd -s 1 -d 'operation not supported %(c %xxd -r -i still impossible)'

