# xxh128sum
# Autogenerated from man page /usr/share/man/man1/xxh128sum.1.gz
complete -c xxh128sum -s V -l version -d 'Displays xxhsum version and exits'
complete -c xxh128sum -o HHASHTYPE -d 'Hash selection.  HASHTYPE means 0=XXH32, 1=XXH64, 2=XXH128, 3=XXH3'
complete -c xxh128sum -l binary -d 'Read in binary mode'
complete -c xxh128sum -l tag -d 'Output in the BSD style'
complete -c xxh128sum -l little-endian -d 'Set output hexadecimal checksum value as little endian convention'
complete -c xxh128sum -s h -l help -d 'Displays help and exits '
complete -c xxh128sum -s c -l check -d 'Read xxHash sums from FILE and check them'
complete -c xxh128sum -s q -l quiet -d 'Don\'t print OK for each successfully verified file'
complete -c xxh128sum -l strict -d 'Return an error code if any line in the file is invalid, not just if some che…'
complete -c xxh128sum -l status -d 'Don\'t output anything.  Status code shows success'
complete -c xxh128sum -s w -l warn -d 'Emit a warning message about each improperly formatted checksum line'
complete -c xxh128sum -s b -d 'Benchmark mode.  See EXAMPLES for details'
complete -c xxh128sum -o 'b#' -d 'Specify ID of variant to be tested'
complete -c xxh128sum -o BBLOCKSIZE -d 'Only useful for benchmark mode (-b).  See EXAMPLES for details'

