# xzegrep
# Autogenerated from man page /usr/share/man/man1/xzegrep.1.gz
complete -c xzegrep -s r
complete -c xzegrep -l recursive -d ' 4'
complete -c xzegrep -s R
complete -c xzegrep -l dereference-recursive -d ' 4'
complete -c xzegrep -s d
complete -c xzegrep -l directories -d ' 4'
complete -c xzegrep -s Z
complete -c xzegrep -l null -d ' 4'
complete -c xzegrep -s z
complete -c xzegrep -l null-data -d ' 4'
complete -c xzegrep -l include -d ' 4'
complete -c xzegrep -l exclude -d ' 4'
complete -c xzegrep -l exclude-from -d ' 4'
complete -c xzegrep -l exclude-dir

