# xzfgrep
# Autogenerated from man page /usr/share/man/man1/xzfgrep.1.gz
complete -c xzfgrep -s r
complete -c xzfgrep -l recursive -d ' 4'
complete -c xzfgrep -s R
complete -c xzfgrep -l dereference-recursive -d ' 4'
complete -c xzfgrep -s d
complete -c xzfgrep -l directories -d ' 4'
complete -c xzfgrep -s Z
complete -c xzfgrep -l null -d ' 4'
complete -c xzfgrep -s z
complete -c xzfgrep -l null-data -d ' 4'
complete -c xzfgrep -l include -d ' 4'
complete -c xzfgrep -l exclude -d ' 4'
complete -c xzfgrep -l exclude-from -d ' 4'
complete -c xzfgrep -l exclude-dir

