# xzgrep
# Autogenerated from man page /usr/share/man/man1/xzgrep.1.gz
complete -c xzgrep -s r
complete -c xzgrep -l recursive -d ' 4'
complete -c xzgrep -s R
complete -c xzgrep -l dereference-recursive -d ' 4'
complete -c xzgrep -s d
complete -c xzgrep -l directories -d ' 4'
complete -c xzgrep -s Z
complete -c xzgrep -l null -d ' 4'
complete -c xzgrep -s z
complete -c xzgrep -l null-data -d ' 4'
complete -c xzgrep -l include -d ' 4'
complete -c xzgrep -l exclude -d ' 4'
complete -c xzgrep -l exclude-from -d ' 4'
complete -c xzgrep -l exclude-dir

