use_nerdfont		= true
vol_norm		= true
cover_max_scale		= 3





[theme]
title			= "light blue"
primary			= "light white"
secondary		= "black"
highlight		= "white"
highlight_bg		= "#484848"
playing			= "light white"
playing_selected	= "light blue"
statusbar 		= "light blue"
cmdline 		= "white"
cmdline_bg 		= "black"